### ISSUE TITLE
Feedback wanted: Add support for remote WRF programs execution

### ISSUE THREAD

**Issue by dmey** [GIS4WRF/gis4wrf#1]
GIS4WRF allows to run WPS and WRF binaries on local systems. The tool could be enhanced by allowing for remote execution of the `wrf` program. 

**In order to offer such support, we first need to understand which platform and job management system is most commonly used by the community.**

**Please add your specific requirements to this thread so that we can have a better idea of your specific requirements.**

**Comment by letmaik** [comment]
Closing due to lack of interest.
