### ISSUE TITLE
Error running Geogrid due to the absence of "con" folder

### ISSUE THREAD

**Issue by temprb** [GIS4WRF/gis4wrf#104]
**Describe the bug**
GIS4WRF crashes while running Geogrid because it does not find data in folder "con" (actually such a folder does not exist under "geog/orogwd_1deg"). I've read that "con" is a special directory in Windows. I have seen a previous issue about the creation of folder "con" and, if I understand it correctly, it has been solved by skipping the creation of the folder with a try/catch.

**To Reproduce**
I was trying to do a simulation similar to the one described in the tutorial. The only differences are that the domain is located in north-western Italy and the date of simulation is October 29, 2018. 

**Expected behavior**
I expected Geogrid to run correctly, as it did on another PC where I did not have the problem.

**Screenshots**
I have not a screenshot, but this is the final line of file geogrid.log.0000 
"2018-11-28 11:43:47.358 --- ERROR: Could not open Z:/test/user1/gis4wrf\datasets\geog/orogwd_1deg/con/index"

**Operating System Information**
 - OS: Windows server 2016
Note 1: In Windows Server 2016 the folder "con" does not exist, while I have verified that on another PC with Windows 10, where I do the simulation without problems, the folder exists (even though when I try to enter the folder I get this error: "Location is not available. The handle is invalid.")
Note 2: I still have QGIS 3.2.3 because when I try to install GIS4WRF in QGIS 3.4 I get an error during the installation of the Python packages (but this is another issue). 

Thanks for your support.

**Comment by dmey** [comment]
Thanks for reporting this but I would like to check a few things first:
- what do you mean by 'crashing'? Do you mean that Python raises an exception when trying to run geogrid? GIS4WRF does not crash as far as I can see.
- We have not tested on Windows server but how did you download the geo data sets? Did you follow the tutorial/documentation exactly to download the geo data sets on WIndows Server or did you deviate? Which geo data sets did you select?

With regards to the `con` folder name on Windows, we do handle it -- see:
https://github.com/GIS4WRF/gis4wrf/blob/71c9972ed52a2040cebb79c31e5a2fbb8bb46972/gis4wrf/core/downloaders/geo.py#L43-L49

So if you downloaded the geo data sets with GIS4WRF, you should have been notified if the extraction failed.

**Comment by temprb** [comment]
Thank you for your rapid answer.

Yes, I did not explain the problem correctly, GIS4WRF does not crash, it is Geogrid that does not terminate correctly because it does not find the "con" folder.

I have downloaded the data as in the tutorial. Once I have defined the domains, from "Datasets | Geo" I have selected the mandatory fields in lowest resolution. I don't remember any error while downloading the data.

Thanks for pointing me to geo.py where you have solved the problem, I did not see it before. That explains why I have the "con" folder in Windows 10. As soon as I have the possibility, I'll try to repeat the simulation on Windows Server and to send you additional information.

Thanks.

**Comment by temprb** [comment]
Hi again,
there was indeed an error while downloading the data, as you wrote. I copy below the Python log contents. "Accesso negato" in the last line means "Access denied". Maybe the method used for the creation of the "con" folder does not work in Windows Server?
Thanks again for your help.

>2018-12-03T14:14:33     WARNING    Traceback (most recent call last):
>              File >"C:/Users/user1/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\plugin\ui\helpers.py", line 333, in reraise
>              raise exc_info[0].with_traceback(*exc_info[1:])
>              File >"C:/Users/user1/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\plugin\ui\thread.py", line 32, in start
>              for progress, status in self.fn():
>              File >"C:/Users/user1/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\plugin\ui\widget_geo.py", line 147, in download_datasets
>              for dataset_progress in download_and_extract_geo_dataset(name, self.options.geog_dir):
>              File >"C:/Users/user1/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\core\downloaders\geo.py", line 49, in download_and_extract_geo_dataset
>              windows_extract_with_reserved_names(str(path_to_archive), str(base_dir))
>              File >"C:/Users/user1/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\core\downloaders\geo.py", line 73, in windows_extract_with_reserved_names
>              os.mkdir(path)
>             PermissionError: [WinError 5] Accesso negato: '\\\\\\\\?\\\\Z:\\\\test\\\\user1\\\\gis4wrf\\\\datasets\\\\geog\\\\orogwd_1deg\\\\con'

**Comment by dmey** [comment]
Thanks for letting me know. I'd be interested to know the reason for this though, if you have a chance to do a quick test , could you try to create it manually from the command prompt (fist without and then with elevated privileges).

E.g., to create it -- 

```
md \\?\Z:\\test\\user1\\gis4wrf\\datasets\\geog\\con
```
to remove it --

```
rd /q /s \\?\Z:\\test\\user1\\gis4wrf\\datasets\\geog\\con
```
I deleted the `orogwd_1deg` from the path as I am not sure if that path exists but you can added it or change the path if you want.

**Comment by temprb** [comment]
I tried to create the directory as you suggested, both with normal and elevated privileges, I always get the same result: "Specified path is not valid". I have verified that the path before "con" exists (including orogwd_1deg) and I can do a dir to it.
Thanks for your support.

**Comment by dmey** [comment]
This appears to work on Windows Server 2016 however there may be some domain policies in your case that restrict this. I would therefore suggest to speak to your system admin in order to resolve this. If you are happy with this, I would close this issue as it does not appear to be relevant to GIS4WRF, but to your specific configuration of Windows Server 2016.

PS If you want to know more about path naming in Windows see https://docs.microsoft.com/en-us/windows/desktop/fileio/naming-a-file

**Comment by temprb** [comment]
Thank you for your help. I'll speak to the system administrator.

**Comment by dmey** [comment]
No problems. I'll close this for now but please do let me know if you get it working. Thanks
