### ISSUE TITLE
Dataset/Met/Extent

### ISSUE THREAD

**Issue by AgroMet** [GIS4WRF/gis4wrf#108]
In Dataset > Met > Extent 
Set from active layer button cannot read active polygon extent into North Latitude East Longitude... boxes

**Comment by letmaik** [comment]
Details please. How did you make the layer active? You need to click on it in the legend. What happens when you click the button? If nothing, please also say so.

**Comment by dmey** [comment]
@AgroMet can you provide more details? Or have you resolved the issue?

**Comment by dmey** [comment]
Closing as no response from the user.
@AgroMet feel free to reopen if the issue persists.
