### ISSUE TITLE
Error in Downloading Met Data

### ISSUE THREAD

**Issue by AgroMet** [GIS4WRF/gis4wrf#109]
**on MacBook Pro 2017: I could run QGIS4WRF based on tutorial successfully. But I changed my domain and when I was trying to download Met data, QGIS4WRF could download part of data but at the middle, I got this error:**

RuntimeError: /Users/myusername/Documents/gis4wrf/datasets/met/ds083.3/Analysis/201806011200-201807071800/gdas1.fnl0p25.2018060112-2018062106.f00.grib2.spasub.lotfi341397.tar is a grib file, but no raster dataset was successfully identified. 
Traceback (most recent call last):
  File "/Users/myusername/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/plugin/ui/widget_datasets.py", line 660, in populate_met_data_tree
    folder_meta, file_metas = read_grib_folder_metadata(time_range_folder)
  File "/Users/myusername/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/core/readers/grib_metadata.py", line 32, in read_grib_folder_metadata
    return read_grib_files_metadata(paths)
  File "/Users/myusername/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/core/readers/grib_metadata.py", line 44, in read_grib_files_metadata
    meta = read_grib_file_metadata(path)
  File "/Users/myusername/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/core/readers/grib_metadata.py", line 60, in read_grib_file_metadata
    ds = gdal.Open(path, gdal.GA_ReadOnly)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/osgeo/gdal.py", line 3087, in Open
    return _gdal.Open(*args)
RuntimeError: /Users/myusername/Documents/gis4wrf/datasets/met/ds083.3/Analysis/201806011200-201807071800/gdas1.fnl0p25.2018060112-2018062106.f00.grib2.spasub.lotfi341397.tar is a grib file, but no raster dataset was successfully identified.

Python version: 3.6.3 (v3.6.3:2c5fed86e0, Oct  3 2017, 00:32:08) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] 
QGIS version: 3.4.4-Madeira Madeira, exported 

Python Path:
/Applications/QGIS3.app/Contents/MacOS/../Resources/python
/Users/myusername/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/myusername/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS3.app/Contents/MacOS/../Resources/python/plugins
/Library/Frameworks/SQLite3.framework/Versions/D/Python/3.6
/Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload
/Users/myusername/Library/Python/3.6/lib/python/site-packages
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
/Users/myusername/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/myusername/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Users/myusername/Library/Application Support/gis4wrf/python36/lib/python3.6/site-packages

**Comment by letmaik** [comment]
For reproducibility, please copy and paste the content of the input fields. Making a screenshot helps as well sometimes.

**Comment by dmey** [comment]
@AgroMet can you provide more details? Or have you resolved the issue?

**Comment by AgroMet** [comment]
Dear gis4wrf developper,

Sorry for the late reply,
First of all, I really appreciate for developing this amazing tool.
I checked it in MacOS, I follow exactly the same steps as you trained in
the website. It has delay to update the lat/long boxes. I mean, I have to
switch between layers few times and then click on the domain layer again,
then push the button several times to update the domain extent! I don't
know why this happen!
I double checked it in windows environment. It works perfect in windows
without any problem.
Anyway,
For your future develops, I highly recommend you to add a drawing polygon
toolbox for determining the domain(s). I understand it needs more time and
support to develop it.
Thank you for your time.

Kind regards,
Hossein

-------------------------------------------------------------
Hossein Lotfi
M.Sc. in Agricultural Meteorology
cell phone: +1 662 617 3345
Email: agri.meteo@gmail.com

**Comment by dmey** [comment]
Closing as no response from the user.
@AgroMet feel free to reopen if the issue persists.
