### ISSUE TITLE
Error in Running Tutorial

### ISSUE THREAD

**Issue by Robin0131** [GIS4WRF/gis4wrf#110]
**Describe the bug**
Nice to meet you!
I downloaded GIS4WRF and tried to run a tutorial.
I've run Geogrid, Ungrib and Metgrid in WPS, and then, it has seemed success.
When I've tried to run real in WRF, the error has not been occurred.
However, the following error has occurred when Run WRF.

What may be the cause?
Thank you for watching!

---------------------------
Command: C:\Users\username\Documents\gis4wrf\dist\WRF-4.0-nompi\main\wrf.exe
Working directory: C:/Users/username/Documents/gis4wrf/projects/2018_07_15_Amsterdam\run_wrf
 Ntasks in X            1 , ntasks in Y            1
*************************************
Configuring physics suite 'conus'

         mp_physics:      8      8
         cu_physics:      6      6
      ra_lw_physics:      4      4
      ra_sw_physics:      4      4
     bl_pbl_physics:      2      2
  sf_sfclay_physics:      2      2
 sf_surface_physics:      2      2
*************************************
WRF V4.0 MODEL
 *************************************
 Parent domain
 ids,ide,jds,jde            1          31           1          31
 ims,ime,jms,jme           -4          36          -4          36
 ips,ipe,jps,jpe            1          31           1          31
 *************************************
DYNAMICS OPTION: Eulerian Mass Coordinate
   alloc_space_field: domain            1 ,              43878196  bytes allocated
  med_initialdata_input: calling input_input
   Input data is acceptable to use: wrfinput_d01
Timing for processing wrfinput file (stream 0) for domain        1:    0.07900 elapsed seconds
Max map factor in domain 1 =  1.51. Scale the dt in the model accordingly.
INPUT LandUse = "MODIFIED_IGBP_MODIS_NOAH"
 LANDUSE TYPE = "MODIFIED_IGBP_MODIS_NOAH" FOUND          33  CATEGORIES           2  SEASONS WATER CATEGORY =           17  SNOW CATEGORY =           15
INITIALIZE THREE Noah LSM RELATED TABLES
Skipping over LUTYPE = USGS
 LANDUSE TYPE = MODIFIED_IGBP_MODIS_NOAH FOUND          20  CATEGORIES
 INPUT SOIL TEXTURE CLASSIFICATION = STAS
 SOIL TEXTURE CLASSIFICATION = STAS FOUND          19  CATEGORIES
ThompMP: computing qr_acr_qg
Writing qr_acr_qg.dat in Thompson MP init
ThompMP: computing qr_acr_qs
Writing qr_acr_qs.dat in Thompson MP init
ThompMP: computing freezeH2O
Writing freezeH2O.dat in Thompson MP init
 *************************************
 Nesting domain
 ids,ide,jds,jde            1          31           1          31
 ims,ime,jms,jme           -4          36          -4          36
 ips,ipe,jps,jpe            1          31           1          31
 INTERMEDIATE domain
 ids,ide,jds,jde            9          24           9          24
 ims,ime,jms,jme            4          29           4          29
 ips,ipe,jps,jpe            7          26           7          26
 *************************************
d01 2018-07-15_12:00:00  alloc_space_field: domain            2 ,               6841120  bytes allocated
d01 2018-07-15_12:00:00  alloc_space_field: domain            2 ,              43878196  bytes allocated
d01 2018-07-15_12:00:00 *** Initializing nest domain # 2 from an input file. ***
d01 2018-07-15_12:00:00 med_initialdata_input: calling input_input
d01 2018-07-15_12:00:00  Input data is acceptable to use: wrfinput_d02
Timing for processing wrfinput file (stream 0) for domain        2:    0.07813 elapsed seconds
INPUT LandUse = "MODIFIED_IGBP_MODIS_NOAH"
 LANDUSE TYPE = "MODIFIED_IGBP_MODIS_NOAH" FOUND          33  CATEGORIES           2  SEASONS WATER CATEGORY =           17  SNOW CATEGORY =           15
INITIALIZE THREE Noah LSM RELATED TABLES
Skipping over LUTYPE = USGS
 LANDUSE TYPE = MODIFIED_IGBP_MODIS_NOAH FOUND          20  CATEGORIES
 INPUT SOIL TEXTURE CLASSIFICATION = STAS
 SOIL TEXTURE CLASSIFICATION = STAS FOUND          19  CATEGORIES
INPUT LandUse = "MODIFIED_IGBP_MODIS_NOAH"
 LANDUSE TYPE = "MODIFIED_IGBP_MODIS_NOAH" FOUND          33  CATEGORIES           2  SEASONS WATER CATEGORY =           17  SNOW CATEGORY =           15
INITIALIZE THREE Noah LSM RELATED TABLES
Skipping over LUTYPE = USGS
 LANDUSE TYPE = MODIFIED_IGBP_MODIS_NOAH FOUND          20  CATEGORIES
 INPUT SOIL TEXTURE CLASSIFICATION = STAS
 SOIL TEXTURE CLASSIFICATION = STAS FOUND          19  CATEGORIES
Max map factor in domain 1 =  1.51. Scale the dt in the model accordingly.
INPUT LandUse = "MODIFIED_IGBP_MODIS_NOAH"
 LANDUSE TYPE = "MODIFIED_IGBP_MODIS_NOAH" FOUND          33  CATEGORIES           2  SEASONS WATER CATEGORY =           17  SNOW CATEGORY =           15
INITIALIZE THREE Noah LSM RELATED TABLES
Skipping over LUTYPE = USGS
 LANDUSE TYPE = MODIFIED_IGBP_MODIS_NOAH FOUND          20  CATEGORIES
 INPUT SOIL TEXTURE CLASSIFICATION = STAS
 SOIL TEXTURE CLASSIFICATION = STAS FOUND          19  CATEGORIES
Timing for Writing wrfout_d01_2018-07-15_12_00_00 for domain        1:    0.10937 elapsed seconds
d01 2018-07-15_12:00:00  Input data is acceptable to use: wrfbdy_d01
Timing for processing lateral boundary for domain        1:    0.06250 elapsed seconds
 Tile Strategy is not specified. Assuming 1D-Y
WRF TILE   1 IS      1 IE     31 JS      1 JE     31
WRF NUMBER OF TILES =   1

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0xffffffff
#1  0xffffffff
#2  0xffffffff
#3  0xffffffff
#4  0xffffffff
#5  0xffffffff
#6  0xffffffff
#7  0xffffffff
#8  0xffffffff
#9  0xffffffff
#10  0xffffffff
#11  0xffffffff
#12  0xffffffff
#13  0xffffffff
#14  0xffffffff
#15  0xffffffff
#16  0xffffffff
#17  0xffffffff
#18  0xffffffff
#19  0xffffffff
Exit code: 3
Runtime: 379 s
---------------------------

**Operating System Information (please complete the following information):**
 - OS: Windows 10 Education, version 1809, build No. 17763.253
 - CPU: Intel Core i7-4790 CPU @ 3.60GHz
 - RAM: 16.0 GB
 - QGIS: Version 3.4.4.
 - Compiler: MinGW-W64 GCC-8.1.0

**Comment by dmey** [comment]
@Robin0131 this looks to me like a misconfiguration rather than an issue with GIS4WRF. I noticed that you have not used the same `namelist.input` as shown in the tutorial -- that is, you have not used the following:

```
&physics
    physics_suite = 'CONUS'
    mp_physics = 0, 0
    cu_physics = 0, 0
    radt = 9, 3
    bldt = 0, 0
    cudt = 0, 0
    icloud = 0
    num_land_cat = 21
    sf_urban_physics = 1, 1
/
```

Can I ask you to please try again following the same configuration as described in the tutorial first and let me know if that works. If that's that works then it's a matter of determining whether the option/s you want to change can work or it's a bug in WRF.

**Comment by Robin0131** [comment]
Thank you for your advice!
When I run the WRF that I revised namelist.input as you pointed out, the error that I asked you in the previous question was not shown.
However, a new error message appeared.

What may be the cause?
Thank you.


Command: C:\Users\username\Documents\gis4wrf\dist\WRF-4.0-nompi\main\wrf.exe
Working directory: C:/Users/username/Documents/gis4wrf/projects/2018_07_15_Amsterdam\run_wrf
 Ntasks in X            1 , ntasks in Y            1
*************************************
Configuring physics suite 'conus'

         mp_physics:      0*     0*
         cu_physics:      0*     0*
      ra_lw_physics:      4      4
      ra_sw_physics:      4      4
     bl_pbl_physics:      2      2
  sf_sfclay_physics:      2      2
 sf_surface_physics:      2      2

(* = option overrides suite setting)
*************************************
WRF V4.0 MODEL
 *************************************
 Parent domain
 ids,ide,jds,jde            1          31           1          31
 ims,ime,jms,jme           -4          36          -4          36
 ips,ipe,jps,jpe            1          31           1          31
 *************************************
DYNAMICS OPTION: Eulerian Mass Coordinate
   alloc_space_field: domain            1 ,              62810520  bytes allocated
  med_initialdata_input: calling input_input
   Input data is acceptable to use: wrfinput_d01
Timing for processing wrfinput file (stream 0) for domain        1:    0.07811 elapsed seconds
Max map factor in domain 1 =  1.51. Scale the dt in the model accordingly.
INPUT LandUse = "MODIFIED_IGBP_MODIS_NOAH"
 LANDUSE TYPE = "MODIFIED_IGBP_MODIS_NOAH" FOUND          33  CATEGORIES           2  SEASONS WATER CATEGORY =           17  SNOW CATEGORY =           15
INITIALIZE THREE Noah LSM RELATED TABLES
Skipping over LUTYPE = USGS
 LANDUSE TYPE = MODIFIED_IGBP_MODIS_NOAH FOUND          20  CATEGORIES
 INPUT SOIL TEXTURE CLASSIFICATION = STAS
 SOIL TEXTURE CLASSIFICATION = STAS FOUND          19  CATEGORIES
 *************************************
 Nesting domain
 ids,ide,jds,jde            1          31           1          31
 ims,ime,jms,jme           -4          36          -4          36
 ips,ipe,jps,jpe            1          31           1          31
 INTERMEDIATE domain
 ids,ide,jds,jde            9          24           9          24
 ims,ime,jms,jme            4          29           4          29
 ips,ipe,jps,jpe            7          26           7          26
 *************************************
d01 2018-07-15_12:00:00  alloc_space_field: domain            2 ,               6292208  bytes allocated
d01 2018-07-15_12:00:00  alloc_space_field: domain            2 ,              62810520  bytes allocated
d01 2018-07-15_12:00:00 *** Initializing nest domain # 2 from an input file. ***
d01 2018-07-15_12:00:00 med_initialdata_input: calling input_input
d01 2018-07-15_12:00:00  Input data is acceptable to use: wrfinput_d02
Timing for processing wrfinput file (stream 0) for domain        2:    0.07011 elapsed seconds
INPUT LandUse = "MODIFIED_IGBP_MODIS_NOAH"
 LANDUSE TYPE = "MODIFIED_IGBP_MODIS_NOAH" FOUND          33  CATEGORIES           2  SEASONS WATER CATEGORY =           17  SNOW CATEGORY =           15
INITIALIZE THREE Noah LSM RELATED TABLES
Skipping over LUTYPE = USGS
 LANDUSE TYPE = MODIFIED_IGBP_MODIS_NOAH FOUND          20  CATEGORIES
 INPUT SOIL TEXTURE CLASSIFICATION = STAS
 SOIL TEXTURE CLASSIFICATION = STAS FOUND          19  CATEGORIES
INPUT LandUse = "MODIFIED_IGBP_MODIS_NOAH"
 LANDUSE TYPE = "MODIFIED_IGBP_MODIS_NOAH" FOUND          33  CATEGORIES           2  SEASONS WATER CATEGORY =           17  SNOW CATEGORY =           15
INITIALIZE THREE Noah LSM RELATED TABLES
Skipping over LUTYPE = USGS
 LANDUSE TYPE = MODIFIED_IGBP_MODIS_NOAH FOUND          20  CATEGORIES
 INPUT SOIL TEXTURE CLASSIFICATION = STAS
 SOIL TEXTURE CLASSIFICATION = STAS FOUND          19  CATEGORIES
Max map factor in domain 1 =  1.51. Scale the dt in the model accordingly.
INPUT LandUse = "MODIFIED_IGBP_MODIS_NOAH"
 LANDUSE TYPE = "MODIFIED_IGBP_MODIS_NOAH" FOUND          33  CATEGORIES           2  SEASONS WATER CATEGORY =           17  SNOW CATEGORY =           15
INITIALIZE THREE Noah LSM RELATED TABLES
Skipping over LUTYPE = USGS
 LANDUSE TYPE = MODIFIED_IGBP_MODIS_NOAH FOUND          20  CATEGORIES
 INPUT SOIL TEXTURE CLASSIFICATION = STAS
 SOIL TEXTURE CLASSIFICATION = STAS FOUND          19  CATEGORIES
Timing for Writing wrfout_d01_2018-07-15_12_00_00 for domain        1:    0.10936 elapsed seconds
d01 2018-07-15_12:00:00  Input data is acceptable to use: wrfbdy_d01
Timing for processing lateral boundary for domain        1:    0.03125 elapsed seconds
 Tile Strategy is not specified. Assuming 1D-Y
WRF TILE   1 IS      1 IE     31 JS      1 JE     31
WRF NUMBER OF TILES =   1
Timing for Writing wrfout_d02_2018-07-15_12_00_00 for domain        2:    0.09376 elapsed seconds
 Tile Strategy is not specified. Assuming 1D-Y
WRF TILE   1 IS      1 IE     31 JS      1 JE     31
WRF NUMBER OF TILES =   1
d02 2018-07-15_12:00:00         9667  points exceeded cfl=2 in domain d02 at time 2018-07-15_12:00:00 hours
d02 2018-07-15_12:00:00  MAX AT i,j,k:            9          30          26  vert_cfl,w,d(eta)=   913266688.      -4.99274035E+09   2.89094970E-02
d02 2018-07-15_12:00:00          955  points exceeded cfl=2 in domain d02 at time 2018-07-15_12:00:00 hours
d02 2018-07-15_12:00:00  MAX AT i,j,k:           12          19          26  vert_cfl,w,d(eta)=   6.15391693E+09   5.80983245E+09   2.89094970E-02
Timing for main: time 2018-07-15_12:01:00 on domain   2:    1.07659 elapsed seconds
-------------- FATAL CALLED ---------------
ZDC + Z0C + 2m is larger than the 1st WRF level Stop in subroutine urban - change ZDC and Z0C
-------------------------------------------
-------------- FATAL CALLED ---------------
ZDC + Z0C + 2m is larger than the 1st WRF level Stop in subroutine urban - change ZDC and Z0C
-------------------------------------------
Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG IEEE_DIVIDE_BY_ZERO IEEE_OVERFLOW_FLAG IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
Runtime: 3 s

**Comment by dmey** [comment]
@Robin0131, it looks like the configuration is still different than what's in the tutorial. Make sure you follow _exactly_ what's in the tutorial -- you need to have the same namelist as used in the tutorial, not just the changes I specifically pointed out in my previous comment. Please see https://gis4wrf.github.io/tutorials/index.html#wrf. If in doubt,please rerun the tutorial from the beginning to make sure that you have followed it correctly.

**Comment by Robin0131** [comment]
Thank you for your advice.
When I ran the WRF as you told, I succeeded in maiking the wrfout.
I'm so sorry I didn't read the website well.
I didn't notice that the namelist.input is on the website.

Thank you very much.

**Comment by dmey** [comment]
No problems -- I am glad you were able to successfully complete the tutorial.
If you encounter problems in the future, when you set-up your own case study and you think that namelist has been configured correctly, it may be worth opening an issue on the [wrfforum](http://forum.wrfforum.com/) or at https://github.com/wrf-model depending on the type of problem. I will close this issue but feel free to open another issue in this repo if you find a bug with GIS4WRF or want to suggest a feature.
