### ISSUE TITLE
Run WRF error exit code: 5 

### ISSUE THREAD

**Issue by jef737** [GIS4WRF/gis4wrf#112]
**Describe the bug**
Hello 
I'm testing GIS4WRF on Linux Unbutu 18.04. I try to reproduce the tutorial with my own domain definition but with the same dimension center point long: 6.7 lat: 45.6. 
Met dataset: ds083.3 product: analysis start date: 06/02/2019 00:00 end date: 06/02/2019 06:00 
Every things work fine up to the step Run WRF 
After about 10mn  i got an error with exit code: 5 
below extract of the prgram output
Command: /home/meteo/gis4wrf/dist/WRF-4.0-nompi/main/wrf.exe
Working directory: /home/meteo/gis4wrf/projects/BSM/run_wrf
 Ntasks in X            1 , ntasks in Y            1
*************************************
Configuring physics suite 'conus'

         mp_physics:      8      8
         cu_physics:      6      6
      ra_lw_physics:      4      4
      ra_sw_physics:      4      4
     bl_pbl_physics:      2      2
  sf_sfclay_physics:      2      2
 sf_surface_physics:      2      2
*************************************
WRF V4.0 MODEL
 *************************************
 Parent domain
 ids,ide,jds,jde            1          31           1          31
 ims,ime,jms,jme           -4          36          -4          36
 ips,ipe,jps,jpe            1          31           1          31
 *************************************
DYNAMICS OPTION: Eulerian Mass Coordinate
   alloc_space_field: domain            1 ,              43878196  bytes allocated
  med_initialdata_input: calling input_input
   Input data is acceptable to use: wrfinput_d01
Timing for processing wrfinput file (stream 0) for domain        1:    0.11406 elapsed seconds
Max map factor in domain 1 =  1.34. Scale the dt in the model accordingly.
INPUT LandUse = "MODIFIED_IGBP_MODIS_NOAH"
 LANDUSE TYPE = "MODIFIED_IGBP_MODIS_NOAH" FOUND          33  CATEGORIES           2  SEASONS WATER CATEGORY =           17  SNOW CATEGORY =           15
INITIALIZE THREE Noah LSM RELATED TABLES
Skipping over LUTYPE = USGS
 LANDUSE TYPE = MODIFIED_IGBP_MODIS_NOAH FOUND          20  CATEGORIES
 INPUT SOIL TEXTURE CLASSIFICATION = STAS
 SOIL TEXTURE CLASSIFICATION = STAS FOUND          19  CATEGORIES
ThompMP: computing qr_acr_qg
Writing qr_acr_qg.dat in Thompson MP init
ThompMP: computing qr_acr_qs
Writing qr_acr_qs.dat in Thompson MP init
ThompMP: computing freezeH2O
Writing freezeH2O.dat in Thompson MP init
 *************************************
 Nesting domain
 ids,ide,jds,jde            1          31           1          31
 ims,ime,jms,jme           -4          36          -4          36
 ips,ipe,jps,jpe            1          31           1          31
 INTERMEDIATE domain
 ids,ide,jds,jde            9          24           9          24
 ims,ime,jms,jme            4          29           4          29
 ips,ipe,jps,jpe            7          26           7          26
 *************************************
d01 2019-02-06_00:00:00  alloc_space_field: domain            2 ,               6841120  bytes allocated
d01 2019-02-06_00:00:00  alloc_space_field: domain            2 ,              43878196  bytes allocated
d01 2019-02-06_00:00:00 *** Initializing nest domain # 2 from an input file. ***
d01 2019-02-06_00:00:00 med_initialdata_input: calling input_input
d01 2019-02-06_00:00:00  Input data is acceptable to use: wrfinput_d02
Timing for processing wrfinput file (stream 0) for domain        2:    0.11466 elapsed seconds
INPUT LandUse = "MODIFIED_IGBP_MODIS_NOAH"
 LANDUSE TYPE = "MODIFIED_IGBP_MODIS_NOAH" FOUND          33  CATEGORIES           2  SEASONS WATER CATEGORY =           17  SNOW CATEGORY =           15
INITIALIZE THREE Noah LSM RELATED TABLES
Skipping over LUTYPE = USGS
 LANDUSE TYPE = MODIFIED_IGBP_MODIS_NOAH FOUND          20  CATEGORIES
 INPUT SOIL TEXTURE CLASSIFICATION = STAS
 SOIL TEXTURE CLASSIFICATION = STAS FOUND          19  CATEGORIES
INPUT LandUse = "MODIFIED_IGBP_MODIS_NOAH"
 LANDUSE TYPE = "MODIFIED_IGBP_MODIS_NOAH" FOUND          33  CATEGORIES           2  SEASONS WATER CATEGORY =           17  SNOW CATEGORY =           15
INITIALIZE THREE Noah LSM RELATED TABLES
Skipping over LUTYPE = USGS
 LANDUSE TYPE = MODIFIED_IGBP_MODIS_NOAH FOUND          20  CATEGORIES
 INPUT SOIL TEXTURE CLASSIFICATION = STAS
 SOIL TEXTURE CLASSIFICATION = STAS FOUND          19  CATEGORIES
Max map factor in domain 1 =  1.34. Scale the dt in the model accordingly.
INPUT LandUse = "MODIFIED_IGBP_MODIS_NOAH"
 LANDUSE TYPE = "MODIFIED_IGBP_MODIS_NOAH" FOUND          33  CATEGORIES           2  SEASONS WATER CATEGORY =           17  SNOW CATEGORY =           15
INITIALIZE THREE Noah LSM RELATED TABLES
Skipping over LUTYPE = USGS
 LANDUSE TYPE = MODIFIED_IGBP_MODIS_NOAH FOUND          20  CATEGORIES
 INPUT SOIL TEXTURE CLASSIFICATION = STAS
 SOIL TEXTURE CLASSIFICATION = STAS FOUND          19  CATEGORIES
Timing for Writing wrfout_d01_2019-02-06_00_00_00 for domain        1:    0.18035 elapsed seconds
d01 2019-02-06_00:00:00  Input data is acceptable to use: wrfbdy_d01
Timing for processing lateral boundary for domain        1:    0.07007 elapsed seconds
 Tile Strategy is not specified. Assuming 1D-Y
WRF TILE   1 IS      1 IE     31 JS      1 JE     31
WRF NUMBER OF TILES =   1
Timing for Writing wrfout_d02_2019-02-06_00_00_00 for domain        2:    0.18884 elapsed seconds
 Tile Strategy is not specified. Assuming 1D-Y
WRF TILE   1 IS      1 IE     31 JS      1 JE     31
WRF NUMBER OF TILES =   1
d02 2019-02-06_00:00:00         5673  points exceeded cfl=2 in domain d02 at time 2019-02-06_00:00:00 hours
d02 2019-02-06_00:00:00  MAX AT i,j,k:           11          30          26  vert_cfl,w,d(eta)=   277298.06      -9927355.0      2.89094970E-02
d02 2019-02-06_00:00:00           42  points exceeded cfl=2 in domain d02 at time 2019-02-06_00:00:00 hours
d02 2019-02-06_00:00:00  MAX AT i,j,k:           30          30          12  vert_cfl,w,d(eta)=   41.793346       340.91577      4.34235930E-02
Timing for main: time 2019-02-06_00:01:00 on domain   2:    0.98528 elapsed seconds
 Flerchinger USEd in NEW version. Iterations=          10
 Flerchinger USEd in NEW version. Iterations=          10

Follow a lot of the same message 

 Flerchinger USEd in NEW version. Iterations=          10
Timing for main: time 2019-02-06_00:06:00 on domain   2:    0.23068 elapsed seconds
Timing for main: time 2019-02-06_00:06:00 on domain   1:    1.39302 elapsed seconds
 Flerchinger USEd in NEW version. Iterations=          10:

Same message again

 Flerchinger USEd in NEW version. Iterations=          10
 Flerchinger USEd in NEW version. Iterations=          10
 Flerchinger USEd in NEW version. Iterations=          10
Timing for main: time 2019-02-06_00:30:00 on domain   2:    0.71218 elapsed seconds
Timing for main: time 2019-02-06_00:30:00 on domain   1:    2.06875 elapsed seconds
Exit code: 5
Runtime: 1006 s

I have seen somewhere a segmentation fault message, but i'm not able to found it among the too lot of messages. May be there is a log file where is easier to check that. Let me know where are the logs file

**Comment by dmey** [comment]
Hi @jef737, thanks for the comprehensive report. I had a quick look at your configuration but it looks different than what at https://gis4wrf.github.io/tutorials/index.html#wrf. For example:
```
&physics
    physics_suite = 'CONUS'
    mp_physics = 0, 0
    cu_physics = 0, 0
    radt = 9, 3
    bldt = 0, 0
    cudt = 0, 0
    icloud = 0
    num_land_cat = 21
    sf_urban_physics = 1, 1
/
```
I would suggest, running the tutorial first exactly as it is on the website if you are not familiar with running WRF. Unfortunately segfaults can happen quite often in WRF due to several different reasons like choice of scheme, time step, etc... If you encounter problems in the future, when you set-up your own case study and you think that namelist has been configured correctly, it may be worth opening an issue on the [wrfforum](http://forum.wrfforum.com/) or at https://github.com/wrf-model depending on the type of problem. I will close this issue but feel free to open another issue in this repo if you find a bug with GIS4WRF or want to suggest a feature.
