### ISSUE TITLE
Standard longitude bug

### ISSUE THREAD

**Issue by hugohartmann** [GIS4WRF/gis4wrf#116]
**Describe the bug**
I have lambert grid where the standard longitude is -10, whereas the center_point longitude = 2. In GIS4WRF, I only have the possibility to set the center_longitude. Inspection of namelist.wps learned me that the standard longitude is set to 2 as well. This is incorrect. 

Changing the standard longitude in namelist.wps, and then "import from namelist" did not show the correct grid, aligned with the -10 longitude line. 

**Expected behavior**
Extra box to provide the standard longitude. In the above example, the grid should be aligned (by rotation) with the longitude line -10, and the center_longitude of the grid should be equal to 2.

**Comment by letmaik** [comment]
You're absolutely right. Thanks for reporting this. I'll do a few more fixes and then attach a pre-release package here (a zip file that you can install in QGIS), so that you can test it before release.

**Comment by letmaik** [comment]
@hugohartmann I fixed the issue and also added support for Mercator and Polar Stereographic projections. If you want to try it before the official release, please download the following zip file: 
[gis4wrf-0.14.0-preview.zip](https://github.com/GIS4WRF/gis4wrf/files/2948574/gis4wrf-0.14.0-preview.zip). To install it, go to the plugin manager of QGIS and on the left side do "Install from ZIP".

**Comment by hugohartmann** [comment]
Thanks! It works like a charm :)
