### ISSUE TITLE
Handle min and max for displaying n time dimensional datasets

### ISSUE THREAD

**Issue by dmey** [GIS4WRF/gis4wrf#120]
Currently, when displaying n time dimensional dataset we do not calculate and set the min and max from all bans before rending the data. I think we should add a global min and max to all bands which is simply the min and max for all times. Furthermore, we should add an option, perhaps under the `Time` slider in the `View` tab to optionally apply the 'local' min and max -- that is, render the band with the min and max calculated from it's specific min and max and not the one from all the other bands.
One important limitation with the global min and max is that spatial differences are visually minimised  therefore the choice of colour maps will become important and we should, in that case, default to one that can enhance differences other than the current grey one.

A way to illustrate this is with the diurnal profile of air temperature over a large area. The air temperature excursion can reach 30 deg C during the day and night but the spatial variability of air temperature across neighbouring cells is rather small leading to the whole domain at a particular time being displayed with a uniform colour, blending any spatial differences in the spatial space.

**Comment by letmaik** [comment]
I don't know what you mean by "n time dimensional dataset".
Also, isn't this a dupe of #89?

**Comment by dmey** [comment]
That's right -- this is a duplicate of #89. I will close this now and add a few comments in #89.
