### ISSUE TITLE
Filename filter not working in "Open WRF NetCDF File" dialog via "Visualize Output" with QGIS 3.6 and Ubuntu 18.04

### ISSUE THREAD

**Issue by pskunjeer** [GIS4WRF/gis4wrf#125]
I have install the plugin on QGIS 3.6. The operating system is Ubuntu 18.04. I have successfully completed the simulation. The WRF process was completed without any error and it created the WRF output files in the wrf_run folder. But when I try to visualize the results from the Visualization tab I am not able to see any output file. 

![WRF_Run_Folder](https://user-images.githubusercontent.com/13337236/54582063-5fa6cd80-4a35-11e9-88db-280ea3af5d9a.png)
![WRF_output_No_File](https://user-images.githubusercontent.com/13337236/54582065-62092780-4a35-11e9-8320-494aabef3053.png)

Additional Information:
I was not able to install wrf-python using pip3. There is was error "pip failed building wheel for wrf-python" so have manually complied the wrf-python from the source. The output of the command "pip3 install --user f90nml pyyaml netCDF4 wrf-python" is as follows
![pip3_install](https://user-images.githubusercontent.com/13337236/54582261-1c009380-4a36-11e9-830e-cdc1f3f855ca.png)

**Comment by letmaik** [comment]
That is curious. As a temporary work-around, please use the menu item in the [Layer menu](https://gis4wrf.github.io/documentation/#layer-menu) as this doesn't have a filename filter. Does that work?

For reference, this is the code that defines the filename filter when clicking on the "[Visualize Output](https://gis4wrf.github.io/documentation/#run)" buttons from the Run tab: https://github.com/GIS4WRF/gis4wrf/blob/f11b563fb712311a6672542be83419a9b3864d66/gis4wrf/plugin/ui/widget_run.py#L157-L173

**Comment by pskunjeer** [comment]
Thanks, Yes that solved the problem

**Comment by letmaik** [comment]
@pskunjeer I found the issue with the filter. The fix will be part of the next release. Thanks again for reporting this.
