### ISSUE TITLE
Changing the version of WRF output

### ISSUE THREAD

**Issue by buseyet** [GIS4WRF/gis4wrf#127]
I need to change the WRF version from 4 to 3. Is there a way for it?

**Comment by dmey** [comment]
Assuming that you have already installed WRF v3.x on your system, sure -- see [this](https://gis4wrf.github.io/configuration/#integration-with-wpswrf) and point to the installation directory. However, if you want to use the pre-compiled binaries we provide -- as we rely on [WRF-CMake](https://github.com/WRF-CMake/WRF) -- we can only support v4 and above.

**Comment by buseyet** [comment]
I use the gis4wrf in QGIS. The version of WRF in gis4wrf is 4. But I need the outputs in v3 because I will use them in another program (MMIF), and the other program needs WRF outputs in v3.

**Comment by buseyet** [comment]
Thanks for the quick answer though

**Comment by dmey** [comment]
GIS4WRF is not tied to a specific version of WRF. We provide pre-built binaries thorough [WRF-CMake](https://github.com/WRF-CMake/WRF) for version 4 and above. If you wish to run an older versions of WRF in GIS4WRF, you will need to compile and install WRF on your system yourself. If that is the case, I would suggest downloading the source files for the version you are looking for from the [WRF releases page](https://github.com/wrf-model/WRF/releases). Please note that we only offer support for [WRF-CMake](https://github.com/WRF-CMake/WRF) and GIS4WRF. For anything else please see the [WRF & MPAS-A Support Forum](http://forum.mmm.ucar.edu/phpBB3/).

**Comment by dmey** [comment]
I will close this now as I think the question has been answered.
