### ISSUE TITLE
How to set a new landmask from user's geotiff file

### ISSUE THREAD

**Issue by taoansf** [GIS4WRF/gis4wrf#131]
Hello friends,

Firstly I would like to congrats you for this very nice gis tool for WRF modelling.

I'm a very new user and I'm needing some help to set some adjustments on my geogrid dataset.
My dificulty is to set a new landmask to my project from a geottif file. I found some ideas for how to personalize geogrid dataset here: 
http://www.met.wur.nl/Summerinthecity/posts/2014/07/wpsgeogridtbl/
https://www.openwfm.org/wiki/How_to_run_WRF-Fire_with_real_data

My first idea was to convert my geotiff to wps format (I got it using gis4wrf process buttom) and edit manually my geogrid.tbl file (inside run_wps/geogrid) before run geogrid. However I noted that this file is changed to default configuration every time I run geogrid using gis4wrf interface. This manner I would like to know how to put my editions on geogrid.tbl file using gis4wrf interface?

Any help will be very appreciated

With best regards,

Taoan

**Comment by letmaik** [comment]
The run_* folders are not meant to be modified. What you can do instead is to change the geogrid.tbl in the parent folder, as this will be copied into the run_wps folder before running WPS. This way you can apply your own customizations. Does that help?

**Comment by taoansf** [comment]
Yes, you are right, it is working now.

Thank you very much!
