### ISSUE TITLE
lowres cannot found under Available Datasets

### ISSUE THREAD

**Issue by buseyet** [GIS4WRF/gis4wrf#132]
After upgrading the gis4wrf, the "lowres" option is not present under the Simulation/Data/Geographical Data/Available Datasets. I downloaded mandatory fields in the lowest resolution

What can I do? Shall I use "default"?

**Comment by letmaik** [comment]
Upgrading gis4wrf has nothing to do with the available datasets. The list simply reflects what is available in your WPS installation in the geogrid/GEOGRID.TBL file.

**Comment by dmey** [comment]
Closing as the question has been answered.

**Comment by buseyet** [comment]
Sure, Thanks!
