### ISSUE TITLE
Use MUR SST DATASETS

### ISSUE THREAD

**Issue by taoansf** [GIS4WRF/gis4wrf#133]
Hello friends,

It is possible to apply Multi-scale Ultra-high Resolution (MUR) Sea Surface Temperature (SST) Analysis with GIS4WRF interface?

There is some way to do it by "Use Custom Dataset" interface buttom?

I have a data set with one year of daily subsets like these below
20170101090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1_subset.nc
... 20171231090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1_subset.nc

Any help will be very appreciated

With best regards,

Taoan

**Comment by dmey** [comment]
I am not familiar with this type of dataset and I am not sure I understand your question -- how would you do this in WRF?

**Comment by taoansf** [comment]
Hello,
My idea is to forcing WRF using high-resolution SST data like this https://www.tceq.texas.gov/assets/public/implementation/air/am/contracts/reports/mm/5821554365FY1501-20150825-aer-high_resolution_met_simulations_DAQ.pdf

I noted that GIS4WRF has a "Use Custom Dataset" interface buttom, which I think could be used to create user defined metgrid forcing for WRF.
![image](https://user-images.githubusercontent.com/22460776/56813660-d0e75680-6813-11e9-8320-b76a72548f80.png)

I hope my question is cleared for you now.

Any suggestion would be very appreciated.

With best regards,

Taoan

**Comment by dmey** [comment]
I think that this would go beyond the initial scope of GIS4WRF for this option to be added to the interface. YOu should be able to still create the domain in the GUI and carry out any other tasks that are not supported in GIS4WRF from the command prompt. I will close this issue now but feel free to let us if you find any other issues with GIS4WRF or if you would like to contribute to the project.
