### ISSUE TITLE
Error in visualize RAINC, RAINNC and QRAIN on GIS4WRF

### ISSUE THREAD

**Issue by dhiegosales** [GIS4WRF/gis4wrf#137]
**Describe the bug**
After simulation is possible to see some vaariables in the output, but the RAINC, RAINNC and QRAIN does not appear outputs. In the first moment I thought that there was no rain ion the simulation, but I oppened the wrfout on the ncview and I could see the rain. I mean, tehere are values of rain in the WRF output arquive, but the plugin can not open it.

**To Reproduce**
1. Run a simulation with rain datas or open a wrf output arquive with this data.
2. Click on the simulation tab and choose "visualize output" (it will open the view tab)
3. Go to RAINC, RAINNC or QRAIN
3. Try to see the simulation for each variable.
4. The dominium keep black (no values) since there are values in the wrf output.

**Expected behavior**
After simulation is exoected that when I click on the RAINC the plugin should be able to read the values tha exist in the WRF output

**Screenshots**
First image: the plugin is not able to open the RAINC data from output
<img width="960" alt="01 RAINC - GIS4WRF" src="https://user-images.githubusercontent.com/43727871/57631093-373ed980-7575-11e9-8c4c-37dec5bd5515.png">
Second image: I opened the RAINC data from output on the linux dispribtion (ncview)
![02 - RAINC - e-WRF](https://user-images.githubusercontent.com/43727871/57631094-37d77000-7575-11e9-813b-9f09a087b718.png)

**Operating System Information (please complete the following information):**
 - I am using a Windows 10 as a host and vbox ubuntu as guest
- The QGIS is 3.6.2 and o plugin is  GIS4WRF

**Additional context**

**Comment by dmey** [comment]
Thanks for the report --would you be able to share a file that show that issue?

**Comment by dhiegosales** [comment]
The arquive is 190mb. What is the best way to share it?

**Comment by dmey** [comment]
What is the size of the smallest domain output? We only need an output file with one or a few timestamps that shows this issue so that we don't have to run the case ourselves. If you don't have one already, can you just  run the simulation to produce a couple of timestamps? You can directly attach the file by dragging and dropping it in this issue.

**Comment by dmey** [comment]
I think this is just a visualisation issue. I was able to display the data:

![image](https://user-images.githubusercontent.com/26348635/57636194-9534e680-75a0-11e9-9db2-94e6526ace44.png)

Can you please try to recompute the histogram? Right click on the layer and click on Properties then 

![image](https://user-images.githubusercontent.com/26348635/57636314-d0371a00-75a0-11e9-9cdf-d3fd0d74aaef.png)

Let me know if this does the job, then we can see if/how to handle these cases better...

**Comment by dhiegosales** [comment]
I have tried it but I got the same behave

1) recalculing histogram
<img width="960" alt="01 Recalculate" src="https://user-images.githubusercontent.com/43727871/57637120-f77def00-7580-11e9-8b5a-7b96917fad34.png">

2) Additionally I have tried it
<img width="960" alt="02 Recalculate2" src="https://user-images.githubusercontent.com/43727871/57637146-0a90bf00-7581-11e9-87e4-2ebae9e05838.png">

3) The some behave was observed. I have tried re-install the plugin as well.. But It continues...
<img width="960" alt="03 Same behave" src="https://user-images.githubusercontent.com/43727871/57637211-31e78c00-7581-11e9-892c-15025a0767bf.png">

**Comment by dmey** [comment]
On 3.6.2 I was able to reproduce the issue you had with recomputing the histogram however I was able to set the max to 0.1 (remember to click apply) to make those pixels show up.

![image](https://user-images.githubusercontent.com/26348635/57777088-e962d680-7718-11e9-9e7c-879e054b53d9.png)

Can you try this first?

**Comment by dmey** [comment]
Closing as no response from user.

**Comment by selamib** [comment]
I have the same issue. I am using QGIS 3.14.16. Everything runs well but there are no rain outputs. Did someone find a way to show them up?

**Comment by dhiegosales** [comment]
Selamibe the problem was just the visualisation. In fact there was a values on each pixel but the Qgis was not showing me. In order to see the values you can check the histogram not identify the minimum and maximum values available in output file and than you can set it up the in the visualisation field in Qgis. Don't forget to set up colors in order to see correctly the outputs. 
But I'm fact I don't used the Qgis to analyze datas. I exported the output file to R and in the Rstudio I created a program do pet and analyze datas.

**Comment by selamib** [comment]
Okay I will try to solve it with Rstudio like you. Thank you

**Comment by sakine3731** [comment]
> Selamibe the problem was just the visualisation. In fact there was a values on each pixel but the Qgis was not showing me. In order to see the values you can check the histogram and identify the minimum and maximum values available in output file. Than you can set it up in the visualisation field in Qgis. Don't forget to set up colors in order to see correctly the outputs. But actually I don't used the Qgis to analyze datas. I exported the output file to R and in the Rstudio I created a program to see and analyze datas.

Hi
I have the same issue.
Unfortunately, I failed to visualize the RAINC map in Linux with ncview
May you share the program code with me?
thank you
best regards
[my email: sakine.koohi3731@gmail.com]
