### ISSUE TITLE
Installation error with QGIS 3.6 Noosa - "an error occurred during the installation  of Python packages""

### ISSUE THREAD

**Issue by antlopes** [GIS4WRF/gis4wrf#138]
System windows 10

**Describe the bug**
RuntimeError: GIS4WRF: Error installing Python packages Log: Added C:\Users\antonio.lopes\AppData\Local\gis4wrf\python37 as module search pathAdded C:\Users\antonio.lopes\AppData\Local\gis4wrf\python37\lib\site-packages as module search pathPackage directory: C:\Users\antonio.lopes\AppData\Local\gis4wrf\python37C:\OSGeo4W64\bin\python-qgis.bat -m pip install --prefix C:\Users\antonio.lopes\AppData\Local\gis4wrf\python37 f90nml==1.0.2 netCDF4==1.4.2 https://ci.appveyor.com/api/buildjobs/o3ow5itmyi8nhhk2/artifacts/wrf_python-1.1.2-cp37-cp37m-win_amd64.whlCollecting f90nml==1.0.2   Using cached https://files.pythonhosted.org/packages/e6/d8/2654f2dbb02562e3b7d98e0948c41cb84dfc866bf0fa9e679744e293292c/f90nml-1.0.2.tar.gz Collecting netCDF4==1.4.2   Using cached https://files.pythonhosted.org/packages/ba/fb/2a8fb99cf26554aecd513764533a4fff376d49b0e7a1c7a99826aa543d25/netCDF4-1.4.2-cp37-cp37m-win_amd64.whl Collecting wrf-python==1.1.2 from https://ci.appveyor.com/api/buildjobs/o3ow5itmyi8nhhk2/artifacts/wrf_python-1.1.2-cp37-cp37m-win_amd64.whl   HTTP error 404 while getting https://ci.appveyor.com/api/buildjobs/o3ow5itmyi8nhhk2/artifacts/wrf_python-1.1.2-cp37-cp37m-win_amd64.whl   Could not install requirement wrf-python==1.1.2 from https://ci.appveyor.com/api/buildjobs/o3ow5itmyi8nhhk2/artifacts/wrf_python-1.1.2-cp37-cp37m-win_amd64.whl because of error 404 Client Error: The specified blob does not exist. for url: https://appveyorcidata.blob.core.windows.net/letmaik-14065/wrf-python-wheels/1-0-15/o3ow5itmyi8nhhk2/wrf_python-1.1.2-cp37-cp37m-win_amd64.whl?sv=2015-12-11&sr=c&sig=83kmujQV6GmvgmYAucslya1cT%2F1VURcHt6hjopNzcgc%3D&st=2019-05-13T15%3A09%3A10Z&se=2019-05-13T15%3A15%3A10Z&sp=r Could not install requirement wrf-python==1.1.2 from https://ci.appveyor.com/api/buildjobs/o3ow5itmyi8nhhk2/artifacts/wrf_python-1.1.2-cp37-cp37m-win_amd64.whl because of HTTP error 404 Client Error: The specified blob does not exist. for url: https://appveyorcidata.blob.core.windows.net/letmaik-14065/wrf-python-wheels/1-0-15/o3ow5itmyi8nhhk2/wrf_python-1.1.2-cp37-cp37m-win_amd64.whl?sv=2015-12-11&sr=c&sig=83kmujQV6GmvgmYAucslya1cT%2F1VURcHt6hjopNzcgc%3D&st=2019-05-13T15%3A09%3A10Z&se=2019-05-13T15%3A15%3A10Z&sp=r for URL https://ci.appveyor.com/api/buildjobs/o3ow5itmyi8nhhk2/artifacts/wrf_python-1.1.2-cp37-cp37m-win_amd64.whl You are using pip version 19.0.3, however version 19.1.1 is available. You should consider upgrading via the 'python -m pip install --upgrade pip' command. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Operating System Information (please complete the following information):**
 - OS: Windows 
 - Version 10

**Additional context**

**Comment by letmaik** [comment]
Thanks for reporting! A fix is on the way and a new version will be released shortly.

**Comment by dmey** [comment]
@antlopes we have just released 0.14.1 that fixes this issue.

**Comment by antlopes** [comment]
Great. Now is functioning.
Tank you and all the best
Antonio
