### ISSUE TITLE
 Installation error with QGIS 3.6.3 Noosa in Linux ubuntu 18.10

### ISSUE THREAD

**Issue by antlopes** [GIS4WRF/gis4wrf#141]
Some problem as #138 with windows 10, this time with Linux Ubuntu 18.10
RuntimeError: GIS4WRF: Error installing Python packages Log: ...
I have tried all possibilities as proposed in #115
Thank you

LOG

Couldn't load plugin 'gis4wrf' due to an error when calling its classFactory() method 

RuntimeError: GIS4WRF: Error installing Python packages Log: Added /home/al/.local/share/gis4wrf/python36/local/lib/python3.6/dist-packages as module search pathAdded /home/al/.local/share/gis4wrf/python36/lib/python3/dist-packages as module search pathAdded /home/al/.local/share/gis4wrf/python36/lib/python3.6/dist-packages as module search pathPackage directory: /home/al/.local/share/gis4wrf/python36/usr/bin/python3 -m pip install --prefix /home/al/.local/share/gis4wrf/python36 f90nml==1.0.2 netCDF4==1.2.9ERROR: Can not combine '--user' and '--prefix' as they imply different installation locations 
Traceback (most recent call last):
  File "/home/al/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/__init__.py", line 39, in bootstrap_with_ui
    for msg_type, msg_val in bootstrap():
  File "/home/al/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/bootstrap.py", line 220, in bootstrap
    for line in run_subprocess(args, LOG_PATH):
  File "/home/al/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/bootstrap.py", line 249, in run_subprocess
    raise subprocess.CalledProcessError(process.returncode, args)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', 'install', '--prefix', '/home/al/.local/share/gis4wrf/python36', 'f90nml==1.0.2', 'netCDF4==1.2.9']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/al/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/__init__.py", line 22, in classFactory
    bootstrap_with_ui(iface)
  File "/home/al/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/__init__.py", line 62, in bootstrap_with_ui
    raise RuntimeError(PLUGIN_NAME + ': Error installing Python packages\nLog:\n' + log) from e
RuntimeError: GIS4WRF: Error installing Python packages
Log:
Added /home/al/.local/share/gis4wrf/python36/local/lib/python3.6/dist-packages as module search pathAdded /home/al/.local/share/gis4wrf/python36/lib/python3/dist-packages as module search pathAdded /home/al/.local/share/gis4wrf/python36/lib/python3.6/dist-packages as module search pathPackage directory: /home/al/.local/share/gis4wrf/python36/usr/bin/python3 -m pip install --prefix /home/al/.local/share/gis4wrf/python36 f90nml==1.0.2 netCDF4==1.2.9ERROR: Can not combine '--user' and '--prefix' as they imply different installation locations

Python version: 3.6.8 (default, Apr  9 2019, 04:59:38) [GCC 8.3.0] 
QGIS version: 3.6.3-Noosa Noosa, 0c5774c 

Python Path:
/usr/share/qgis/python
/home/al/.local/share/QGIS/QGIS3/profiles/default/python
/home/al/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/python3.6/lib-dynload
/usr/local/lib/python3.6/dist-packages
/usr/lib/python3/dist-packages
/home/al/.local/share/QGIS/QGIS3/profiles/default/python
/home/al/.local/share/gis4wrf/python36/local/lib/python3.6/dist-packages
/home/al/.local/share/gis4wrf/python36/lib/python3/dist-packages
/home/al/.local/share/gis4wrf/python36/lib/python3.6/dist-packages

**Comment by letmaik** [comment]
Please install the required dependencies from the terminal:
pip3 install --user f90nml pyyaml netCDF4 wrf-python

Copy-paste the full log from the terminal in this issue. That will give some insight to what the problem is.

**Comment by antlopes** [comment]
Thank you
This time is solved although I have tried before.
Excellent work.
