### ISSUE TITLE
WRF Domains (Vectors) not displayed when opening a QGIS project

### ISSUE THREAD

**Issue by dmey** [GIS4WRF/gis4wrf#142]
**Describe the bug**
The WRF Domains (Vectors) are not shown on the QGIS canvas even though they are shown in the `Layers` panel when reloading a QGIS project (qgz).

**To Reproduce**
1. Create WRF Domains (Vectors) using the `Domain` tab in GIS4WRF.
1. Go to `Projects` > `Save as...` and save the project.
2. Close and re-open the project.

**System Information:**
 - OS: Windows 10
 - GIS4WRF: 0.14.1
 - QGIS: 3.6.2

**Comment by letmaik** [comment]
Saving/restoring QGIS projects is not supported for GIS4WRF currently. You can however just load the GIS4WRF project up again, which will restore the domains. I don't think it's worth the effort, therefore closing it.
