### ISSUE TITLE
Problem to run WRF with high resolution SST data input

### ISSUE THREAD

**Issue by taoansf** [GIS4WRF/gis4wrf#143]
Hello

I'm looking for a solution to run WRF using high resolution SST data based on this tutorial http://www2.mmm.ucar.edu/wrf/OnLineTutorial/CASES/SST/index.php

After some effort a got this error

![image](https://user-images.githubusercontent.com/22460776/59723814-0b5ee580-91fe-11e9-8bee-787256baea2f.png)

I believe that the problem is due differences on input data. The tutorial uses 0.5 degree data but in my case I have to use 1/12 degree because 0.5 data was discontinued.
![image](https://user-images.githubusercontent.com/22460776/59723411-efa70f80-91fc-11e9-9bd5-13e5d358a7c0.png)

My input data for testing
noaa 1/12 data [rtg_sst_grb_hr_0.083.20150115.grb.zip](https://github.com/GIS4WRF/gis4wrf/files/3303642/rtg_sst_grb_hr_0.083.20150115.grb.zip)
Metgrid output for WRF run [met_em.d01.2015-01-15_00_00_00.nc.zip](https://github.com/GIS4WRF/gis4wrf/files/3303635/met_em.d01.2015-01-15_00_00_00.nc.zip)
Namelist input file [namelist.zip](https://github.com/GIS4WRF/gis4wrf/files/3303636/namelist.zip)

Thank you for any help.

With best regards,

Taoan

**Comment by dmey** [comment]
I don't think that this issue is related with GIS4WRF. I would recommend seeking help on the [WRF forum](http://forum.mmm.ucar.edu/phpBB3/). Here, we only provide support specific to GIS4WRF. I am going to close this issue for now but feel to come back to us if the issue only happens when using GIS4WRF.
