### ISSUE TITLE
PYTHONE ERROR

### ISSUE THREAD

**Issue by falahf** [GIS4WRF/gis4wrf#150]
Hello all here
I am new with GIS4WRF and faced a problem
I appreciate any help

+the problem:

I could download GEO data successfully, but when i turn to next step for met data, the product box doesn't contain any option. and shows pythone error.

 
![NO PRODUCT OPTIONS](https://user-images.githubusercontent.com/53464247/69749666-d8e7db80-10ff-11ea-9e04-f535979a0869.png)

![pythone error](https://user-images.githubusercontent.com/53464247/69750005-91ae1a80-1100-11ea-8530-e91f9894d397.png)

**Comment by letmaik** [comment]
It says "Unauthorized", which means that you didn't put in your RDA username/password correctly in the GIS4WRF settings. See the documentation for details.

**Comment by falahf** [comment]
Thanks alot dear friend
I will check it

در تاریخ چهارشنبه ۲۷ نوامبر ۲۰۱۹،‏ ۲۳:۱۳ Maik Riechert <
notifications@github.com> نوشت:

**Comment by letmaik** [comment]
For the record, this error can also appear with an existing account where data download worked in the post. In that case, the solution is to log in to the RDA website once. I had to accept a license agreement after which it worked again.

**Comment by falahf** [comment]
thanks a million dear friend
I have logged in RDA again.
again GEO data successfully were downloaded.
and in MET phase.....this was the error (pic:  METdownload. python error). again i turned the circumvention off, it began working, but with RDA error (METdownload. error2). would you mind help me with this?
is it possible to talk in telegram messenger?
![Uploading METdownload. error2.png…]()

![Uploading METdownload. python error.png…]()

**Comment by falahf** [comment]
![METdownload  error2](https://user-images.githubusercontent.com/53464247/72200063-8b96a380-33f9-11ea-9930-d8ea3dee17c8.png)
![METdownload  python error](https://user-images.githubusercontent.com/53464247/72200066-905b5780-33f9-11ea-9c76-b23caacc8578.png)

**Comment by letmaik** [comment]
@falahf Please open a new issue, as your original authentication problem was solved.
