### ISSUE TITLE
"unsupported axis order: lat/lon" while converting an imported tiff file from arcmap

### ISSUE THREAD

**Issue by melika1389** [GIS4WRF/gis4wrf#165]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by letmaik** [comment]
Can you please fill in the issue template?

**Comment by melika1389** [comment]
Hello there,
I need to create the input files of wrf-hydro with WPS.
The dataset that I am using is not within the common datasets of WPS.
I was trying to convert the clipped tiff file that I had created in ArcMap to binaries using gis4wrf.
The only steps that I have taken until now are:
1- Opening the raster files and defining their geographical information system as wps84 
2- I had separate rasters, so using the mosaic to new raster, I merged them.
3- I had the shapefile of my region, so I clipped the raster and then added the geographical information system again and exported the file to a new tiff file. 
4- Using add raster layer in qgis, I imported the file. 
5- In the GIS4WRF,  using the Datasets tab and then Process tab, I converted the active layer to binaries. 
6- Then it asked me if the layer is categorical, and I responded no. As my raster dataset is a dem file.
7- Next, it asked me to select the WPS Binary File Output folder, and I selected it, and I faced the following error. 
GIS4WRF-Unsupported feature
Unsupported axis order:Lat/Lon, must be Lon/Lat. Interesting in making GIS4WRF better? Consider contributing code or adding a feature request.

When I am looking at the layer in qgis everything is fine, and qgis can recognize it, but it even does not allow me to export the tiff file.
I am using windows 10 and qgis 3.10.2.
![9](https://user-images.githubusercontent.com/51966054/75258298-40bbca00-57b4-11ea-9a37-35c1cdf68354.PNG)

**Comment by letmaik** [comment]
Which coordinate reference system does the layer have?

**Comment by melika1389** [comment]
It is WGS84 - EPSG 4326

**Comment by dmey** [comment]
@melika1389 please ensure that your GEOTIFF axis are ordered Lon/Lat. rather than Lat/Lon

**Comment by pratiman-91** [comment]
I am also having the same problem. How can we check for the GeoTIFF axis are ordered Lon/Lat rather than Lat/Lon? If it is ordered Lon/Lat then how to convert it to Lat/Lon? 

Any help is appreciated.

**Comment by letmaik** [comment]
Thanks everyone for providing feedback. I reproduced the issue and a fix will be in the next gis4wrf version. A temporary work-around is to use a QGIS version which uses GDAL < 3 (see Help -> About).
