### ISSUE TITLE
"RAIN" parameter not available and QRAIN absent ?

### ISSUE THREAD

**Issue by Jorisjoj** [GIS4WRF/gis4wrf#169]
** Describe the bug **
Hello,

During WRF simulations, certain parameters do not notably display "RAIN C, RAINNC ... ACSWDNB".
The output raster indicates min / max values = 0, the same for the histogram. I used Panoply to view the file on another medium, it's the same thing.

**Reproduce**
Launched a WRF simulation from external GFS data or download analysis.

** Predictable behavior **
Precipitation data for example. They are present in the basic GFS file as well as in the geographic area concerned.

** System information (please complete the following information): **
- OS: Windows 10 family
- QGIS: 3.10.4

** Additional context **
-I have noticed that other users have "QRAIN"? It does not appear in my variables

-The configuration is the same as that of the tutorial

I cannot perform a test on my other computer because it works with Opensuse with QGIS 3.12 and GIS4WRF crashes at launch.

![c1](https://user-images.githubusercontent.com/63890531/79626834-adf43780-8133-11ea-8b3c-021545a2b7a2.PNG)
![c2](https://user-images.githubusercontent.com/63890531/79626838-b77d9f80-8133-11ea-8590-2c2821e1b831.PNG)

**Comment by dmey** [comment]
I think this is related to https://github.com/GIS4WRF/gis4wrf/issues/137#issuecomment-491886067 -- can you let me know if this solves it?

**Comment by Jorisjoj** [comment]
> Je pense que cela est lié à [# 137 (commentaire)](https://github.com/GIS4WRF/gis4wrf/issues/137#issuecomment-491886067) - pouvez-vous me faire savoir si cela le résout?

Hello,
I had already read this post. I even downloaded the exchanger file in this post for comparison and it seems to be the same problem.

However it makes it totally impossible to recalculate the histogram. Everything remains set to "0" regardless of handling. I cannot modify the interval and it turns gray when I click on "calculate the historgamme" (see image)

I enclose the "wrfout"
![c3](https://user-images.githubusercontent.com/63890531/79643312-b0da4100-81a2-11ea-904d-97bad2a2b969.PNG)
[wrfout_d02_2020-02-09_18_00_00.zip](https://github.com/GIS4WRF/gis4wrf/files/4497023/wrfout_d02_2020-02-09_18_00_00.zip)

**Comment by dmey** [comment]
OK but I do not understand what your issue is -- I checked and for the quantities you described (`RAINC`, `RAINNC` `ACSWDNB`), these are all zero in the file you sent me so the display is correctly done in GIS4WRF.

**Comment by Jorisjoj** [comment]
> OK mais je ne comprends pas quel est votre problème - j'ai vérifié et pour les quantités que vous avez décrites ( `RAINC`, `RAINNC` `ACSWDNB`), elles sont toutes nulles dans le fichier que vous m'avez envoyé afin que l'affichage se fasse correctement dans GIS4WRF.

The problem is there, there should be values since in the input file, the precipitation is present in the input data.
However, WRFOUT However, WRFOUT gives no values, and I send the file to see if it was a display problem like in # 137, or a software bug.

**Comment by dmey** [comment]
> The problem is there, there should be values since in the input file, the precipitation is present in the input data.
>However, WRFOUT gives no values, and I send the file to see if it was a display problem like in # 137, or a software bug.

Not necessarily -- most likely, it is due to specific options in the WRF configuration file. WRF is not an easy model to configure and, if you are new, I'd recommend first reading the [user's guide](https://www2.mmm.ucar.edu/wrf/users/docs/user_guide_v4/v4.0/contents.html) or contacting the [WRF support forum](https://www2.mmm.ucar.edu/wrf/users/supports/wrfhelp.html). 

In any case, this does not appear to be an issue related to GIS4WRF so I am will close this issue but feel free to open a new issue in the future if you encounter a problem with GIS4WRF.
