### ISSUE TITLE
GIS4WRF doesn't work on my Qgis 3.12 Linux

### ISSUE THREAD

**Issue by massimodisidoro** [GIS4WRF/gis4wrf#170]
Hello, 
I installed and used the plugin in QGIS 3.10 and everything worked properly.
Now, after several months I tried to use it again (meanwhile, the usual Linux Mint system software updates have been made, including the upgrade to QGIS 3.12) and I have an error launching QGIS.
I don't know if the problem is related to any local configuration in my system (I'm not an expert) or to some bug into the plugin or in the QGIS 3.12 version.

At launching QGIS, a popup appears:
![image1](https://user-images.githubusercontent.com/49653612/81792836-e277cb00-9508-11ea-8b2d-62a50fc9bcd0.png)

Then I push "OK" and  the following appears:
![image2](https://user-images.githubusercontent.com/49653612/81792898-f7ecf500-9508-11ea-8008-62bd6f6383c2.png)

Finally the following log is showed:

[error.log](https://github.com/GIS4WRF/gis4wrf/files/4620769/error.log)

Then QGIS starts normally, the plugin results as installed looking at "Manage and install plugins..." but it is not possible to use it (doesn't appear in plugins menu nor in "Settings -> Options..."

**System Information (please complete the following information):**
 - OS:  Linux Mint 19 Tara (4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux)
 - QGIS: 3.12.2-București

Best regards,
Massimo

**Comment by letmaik** [comment]
Not sure, but you can work around it by manually installing the required packages to your system with `sudo python3 -m pip install f90nml==1.0.2 netCDF4==1.2.9`.

**Comment by massimodisidoro** [comment]
Thank you so much letmaik for your quick reply. Your solution worked!

I close the issue.

Thank you again
Massimo
