### ISSUE TITLE
How to read gis4wrf by ARWpost

### ISSUE THREAD

**Issue by hoangnghiem72** [GIS4WRF/gis4wrf#172]
I run gis4wrf successfully and got the output data. I want to apply the post-proceesing ARWpost to convert the output dataset to ready data display by GrADs. But when I try to run ARWpost with the gis4wrf the error occurred. 

Could you please advise me how can I resolve this problem.

Thanks!

**Comment by dmey** [comment]
I do not know about ARWpost. I looked at https://ruc.noaa.gov/wrf/wrf-chem/tutorial_arwpost.htm and this seems to be a WRF-specific feature. Are you looking to run this as part of GIS4WRF or are you looking for the `ARWpost.exe` program?

**Comment by hoangnghiem72** [comment]
I would like to use  ARWpost which is WRF Post-Processing Software to read and convert the output from WRF to ready data for display on GrADs. It seem to be the ARWpost is not compatible with the output from gis4WRF. Please let me know about that or advise me how to readf and extract data from gis4WRF output data.

**Comment by dmey** [comment]
I am not sure by what you mean by 'outputs from GIS4WRF' -- these are just WRF model outputs (version 4 and above). Are you sure that ARWpost is compatible with recent version of WRF?

**Comment by hoangnghiem72** [comment]
I mean the WRF model outputs running on gis4wrf.  Yes, I  have tried to run ARWpost successfully with the WRF version 4.2. Actually, I need to know are there the post-processor WRF model outputs running on gis4wrf.

**Comment by dmey** [comment]
There is nothing special about GIS4WRF if you are using it to simply run WRF. GIS4WRF simply invokes WRF so if you are using the same namelist configurations and WRF versions you should not get any issues. Can you check that you are running the same version with same configurations?

**Comment by dmey** [comment]
closing as no response from the user
