### ISSUE TITLE
ModuleNotFoundError: No module named 'f90nml'

### ISSUE THREAD

**Issue by pskunjeer** [GIS4WRF/gis4wrf#173]
Couldn't load plugin 'gis4wrf' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'f90nml'

ModuleNotFoundError: No module named 'f90nml' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/emsuser/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/__init__.py", line 24, in classFactory
    from gis4wrf.plugin.plugin import QGISPlugin
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/emsuser/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/plugin/plugin.py", line 17, in 
    from gis4wrf.core import (
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/emsuser/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/core/__init__.py", line 14, in 
    from gis4wrf.core.readers.namelist import *
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/emsuser/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/core/readers/namelist.py", line 10, in 
    import f90nml
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'f90nml'

Python version: 3.8.2 (default, Apr 27 2020, 15:53:34) [GCC 9.3.0] 
QGIS version: 3.10.4-A Coruña A Coruña, exported 

Python Path:
/usr/share/qgis/python
/home/emsuser/.local/share/QGIS/QGIS3/profiles/default/python
/home/emsuser/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python38.zip
/usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/home/emsuser/.local/lib/python3.8/site-packages
/usr/local/lib/python3.8/dist-packages
/usr/lib/python3/dist-packages
/home/emsuser/.local/share/QGIS/QGIS3/profiles/default/python
/home/emsuser/.local/share/QGIS/QGIS3/profiles/default/python/plugins/SwapVectorDirection
/home/emsuser/.local/share/gis4wrf/python38/local/lib/python3.8/dist-packages
/home/emsuser/.local/share/gis4wrf/python38/lib/python3/dist-packages
/home/emsuser/.local/share/gis4wrf/python38/lib/python3.8/dist-packages
/home/emsuser/.local/share/QGIS/QGIS3/profiles/default/python/plugins/crayfish/gui/../pyqtgraph-0.10.0-py2.py3-none-any.whl

**System Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - QGIS: 3.10.0

**Additional context**

**Comment by dmey** [comment]
What installation steps did you follow to install GIS4WRF?

**Comment by pskunjeer** [comment]
I have plugin installed already and working. When I upgraded to Ubuntu 20.04 and QGIS 3.10 it stopped working with the above error. I tried to reinstall from the QGIS plugin manager but it did not work.

**Comment by dmey** [comment]
We did not add specific instructions for 20.04 but you should be able to modify the ones at https://gis4wrf.github.io/installation/#18x-bionic for 20.04. Your error was specific about `f90nml` so you can try to reinstall the required dependencies with `pip3 install --user f90nml pyyaml netCDF4 wrf-python`  (see https://gis4wrf.github.io/installation/#18x-bionic) and backtrack from there. Let me know if this helps.

**Comment by pskunjeer** [comment]
I was able to install the plugin using above mentioned info. Thanks
