### ISSUE TITLE
subtab locked

### ISSUE THREAD

**Issue by madoufanchon** [GIS4WRF/gis4wrf#179]
Hello 

I try tu use the plugin GIS4WRF but I can't use it 
I download the data NCAR, but I can't analyse it 
The subtab stay locked, so I can't select anything 

sub tab : dataset > Met > Product (inacessible)

![InkedAnnotation 2020-08-19 115459_LI](https://user-images.githubusercontent.com/69811628/91022590-b551b300-e5f5-11ea-8281-5b2806d541a0.jpg)

 - OS:  [Windows 10]
 - QGIS: [3.14.0]
- GIS4WRF : [0.14.3]

sincerely yours @dmey

**Comment by dmey** [comment]
I cannot see any issues at my end -- can you confirm that you have configured the Integration with NCAR's Research Data Archive, see https://gis4wrf.github.io/configuration/#integration-with-ncars-research-data-archive. You need to register with NCAR first and then add your username and password to GIS4WRF.

**Comment by dmey** [comment]
Can you access https://rda.ucar.edu/apps/metadata/ds083.3/ from your browser? If you can, please check the username and password you used in GIS4WRF as it's likely incorrect. If you cannot access https://rda.ucar.edu/apps/metadata/ds083.3/ from your browser it is likely due to your network (e.g. blocked by firewall, etc)

**Comment by madoufanchon** [comment]
Hello @dmey 

I close to finish the tuturial but I have an other error 
with subset simulation > run 
I have two errors with metgrid and geo grid 

Software can't open index 
GEOGRID
![error_geogrid](https://user-images.githubusercontent.com/69811628/91838345-9edad580-ec4d-11ea-8d87-53d21ebcfb52.PNG)
METGRID
![error_metgrid](https://user-images.githubusercontent.com/69811628/91838384-aef2b500-ec4d-11ea-9d9e-8435052b786e.PNG)

I wonder if you propose some formations for the plugin ? 

Sincerely yours

**Comment by dmey** [comment]
The error show a problem with opening the gmted 2010 dataset, but I don;t use that in the tutorial. Make sure that you are configuring the geographical datasets sections correctly. Try going through the tutorial again and make sure that you follow each step exactly.  And not at the moment due to time constraints but feel free to open issues or even contribute to the documentation by sending pull requests.

**Comment by madoufanchon** [comment]
hello @dmey 

I tried four times, i uninstall 
but the problem still there
You said don't use gmted 2010 but when i check tutorial, it is included in datas downloads 

![gmted_2010](https://user-images.githubusercontent.com/69811628/92257558-b4623080-eed5-11ea-9857-19b2858de80d.PNG)

sincerely yours

**Comment by dmey** [comment]
The error you showed me above shows that you are using the one at 30 s resolution not the one at 5 min like described in the tutorial.
![image](https://user-images.githubusercontent.com/26348635/92257908-4407df00-eed6-11ea-9f1a-671d545fce27.png)

So all I can suggest is to rerun the totorial caregfull and make sure that `lowres` is selected for both domains as shown in the figure below.

![image](https://user-images.githubusercontent.com/26348635/92258017-79143180-eed6-11ea-98c8-1b8e458c04dc.png)

**Comment by madoufanchon** [comment]
I select it for both 
could you take remote control of my computer (screen sharing) and check it 

because I can be sure I did all like you discribe it

**Comment by dmey** [comment]
Please try to change the working directory for GIS4WRF to a folder without spaces e.g. `C:\Users\franc\Documents\gis4wrf`. You can do this fro QGIS > Settings > Options > GIS4WRF > Working Directory. Then restart QGIS and do the tutorial again from scratch (including download all data). This should do the trick. Let me know how it goes.

**Comment by letmaik** [comment]
I would suggest not to put the gis4wrf folder inside the OneDrive folder, worth a try...

**Comment by madoufanchon** [comment]
hello @dmey 

I finish the tutorials
Thank you for all advices and patience
Let me know when you can make formation 

I start to understand some little things 
I would like try an other simulation but i'm not sure to fixe well all parameters

Sincerely yours
