### ISSUE TITLE
Program received signal SIGSEGV: Segmentation fault - invalid memory reference

### ISSUE THREAD

**Issue by raffyjef** [GIS4WRF/gis4wrf#181]
In the GIS4WRF, WRF will run for at least 10 mins but will terminate and give an error message, "Program received signal SIGSEGV: Segmentation fault - invalid memory reference. I am not good on programming and I am trying to use GIS4WRF to use GIS easier. I tried researching and it seems that the problem is on the cores being used. How do I change the number of cores in the GIS4WRF?

**Comment by dmey** [comment]
https://gis4wrf.github.io/configuration/#integration-with-wpswrf

**Comment by dmey** [comment]
@raffyjef is this fixed?

**Comment by raffyjef** [comment]
I don't know. There are times that I experience this error. But when I try
to reinstall the plug-in, it works fine again.

**Comment by dmey** [comment]
Reinstalling wouldn't solve anything. I suspect this is something to do with a specific configuration you are using. Did you ever get this error when running the tutorial? And if so how many CPUs did you select?

**Comment by raffyjef** [comment]
Yeah, maybe it is in the configuration. However, I can't determine where. I
was using 2 when I got the error.

**Comment by dmey** [comment]
OK. I will close this now as it is unlikely related to GIS4WRF but more with WRF (specific configuration). The community at https://forum.mmm.ucar.edu/phpBB3/ may be able to help you with configuration etc.
