### ISSUE TITLE
Unsupported axis order: Lat/Lon, must be Lon/Lat.

### ISSUE THREAD

**Issue by raffyjef** [GIS4WRF/gis4wrf#191]
I am trying to convert SRTM dataset 1-arcsecond to WPS binary. However, I am receiving this message: Unsupported axis order: Lat/Lon, must be Lon/Lat. 

How do I solve this problem? Thank you.

**Comment by dmey** [comment]
Duplicate of https://github.com/GIS4WRF/gis4wrf/issues/165. The new version should be available for download soon from https://plugins.qgis.org/plugins/gis4wrf/ but in the meantime you can download and install it manually from https://github.com/GIS4WRF/gis4wrf/issues/190

**Comment by dmey** [comment]
Version 0.14.4 is now available at https://plugins.qgis.org/plugins/gis4wrf/

**Comment by raffyjef** [comment]
Thank you!
