### ISSUE TITLE
AttributeError: module 'gis4wrf' has no attribute 'plugin'

### ISSUE THREAD

**Issue by chris18191819** [GIS4WRF/gis4wrf#193]
I have run the plugin , as suggested in website (https://gis4wrf.github.io/tutorials/gis4wrf/simulate-the-2018-european-heat-wave-with-gis4wrf/)  and i have changed the physics to my requirement , as following 
![image](https://user-images.githubusercontent.com/72200155/94800526-0028cc80-03e5-11eb-8ddb-2bd6596fd5e5.png)

I ran WRF successfully and when i want to visualize my output , i get the following error . 
![image](https://user-images.githubusercontent.com/72200155/94800741-5138c080-03e5-11eb-86bb-dbbdf5d286ca.png)

Please help me with the the above mentioned problem . Thanks in advance 

 - OS: Windows 10
 - QGIS: 3.8.0

**Comment by dmey** [comment]
Your modified PYTHONPATH looks like the cause of this issue. I would suggest using what comes with QGIS. Also, please install the latest version of QGIS and use that with GIS4WRF -- You can have more than one version installed at the same time on Windows.

**Comment by dmey** [comment]
@chris18191819 did you solve the issue?

**Comment by dmey** [comment]
Closing as no response from user.
