### ISSUE TITLE
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url

### ISSUE THREAD

**Issue by crlsandres** [GIS4WRF/gis4wrf#194]
Hi, 

I'm new in QGIS4WRF, I'm having an error downloading Met data sets, i configured mi username and password (see picture)

![image](https://user-images.githubusercontent.com/30421207/95669681-df7d1700-0b48-11eb-8799-1e8bcb03ccda.png)

And I'm getting this error

-----------------------------------------------------------------------------------------------            
2020-10-10T22:28:49     WARNING    Traceback (most recent call last):
              File "C:/Users/PERSONAL/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\plugin\ui\widget_met.py", line 129, in on_dataset_changed
              self.products = get_met_products(dataset_name, auth)
              File "C:/Users/PERSONAL/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\core\downloaders\met.py", line 28, in get_met_products
              response.raise_for_status()
              File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\requests\models.py", line 941, in raise_for_status
              raise HTTPError(http_error_msg, response=self)
             requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://rda.ucar.edu/apps/metadata/ds083.3
-------------------------------------------------------------------------------------------------------------------------
I confirme my username and password in https://rda.ucar.edu/ and i was able to login, so credentials are ok, I don't know what i'm doing wrong, could you pelease help me?

**System Information (please complete the following information):**
 - OS: Windows 10
 - QGIS: QGIS Desktop 3.10.9

![image](https://user-images.githubusercontent.com/30421207/95669764-b610bb00-0b49-11eb-9b14-5dbb948a7776.png)

**Comment by dmey** [comment]
Can you try to enter https://rda.ucar.edu/apps/metadata/ds083.3 from your browser and authenticate? What happens?

**Comment by crlsandres** [comment]
return this:

![image](https://user-images.githubusercontent.com/30421207/95681971-6b725b80-0ba8-11eb-8558-e4f3fb4773a7.png)

**Comment by dmey** [comment]
Thanks -- try from a private window to avoid using cached logins. Then when it prompts for username and password enter your details. If these work from the browser, I would suggest recheck carefully that you have entered the correct username and password in GIS4WRF -- there is nothing really special about how we handle authenticate for RDA and the error you reported is about authentication and not connection so I assume that that goes through fine. I have just tried at my end my could not find issues with it although I was able to reproduce the same error by entering the wrong password. Let me know how it goes with this and if it's still not working we can investigate further.

**Comment by crlsandres** [comment]
It does not let me loggin in private mode, I changed my password and even with that does not let me loggin in private mode, and also does not let me loggin with GIS4WRF, there is something wired with my account, I will try to create a new one.

**Comment by crlsandres** [comment]
Hi, there was an issue accepting terms of use in my account, connection with ucar is working fine now.

Thanks a lot.

**Comment by dmey** [comment]
Great! 👍
