### ISSUE TITLE
unsupported axis order: lat/lon error converting raster layer SRTM geotiff to WPS

### ISSUE THREAD

**Issue by Schuch666** [GIS4WRF/gis4wrf#198]
Hi,

I have this error converting the active layer o WPS:

'unsupported axis order: lat/lon, must be Lon/Lat ...'

To reproduce this error:
1 - Download/Open SRTM file(s) from http://srtm.csi.cgiar.org/srtmdata
2 - Merge a number of the desired (optional)
2 - Remove values < 0 of this layer with raster calculator (optional)
3 - Set Layer CSR to WGS84 EPSG 4326 (optional)

I saw that this error was fixed in the latest version 0.14.4 but it still appears, the GDAL version is 3.1.4 and this error appears regardless of the steps marked as optional.

I read the other closed topics related to this problem but none of the solutions worked, is there a way to convert this layer to 'Lon/Lat'? or a different approach? this data is a geotiff without projection.

I'm using QGIS 3.16.1-Hannover in Windows 10.

Thank you

**Comment by letmaik** [comment]
I just tried it out with QGIS 3.16.1 on Windows 10 and it works. I didn't do any of the optional steps, simply downloaded one of the zips (http://srtm.csi.cgiar.org/wp-content/uploads/files/srtm_5x5/tiff/srtm_39_02.zip) and opened the geotiff file. Not sure what could be going on in your case.

**Comment by Schuch666** [comment]
Hi @letmaik 

Thanks for your quick reply

I'm making a new test: saving the geotiff in a different file, close and reopen QGIS and use this new file (including my processing).

As soon as I finish I update with the result of this test

**Comment by Schuch666** [comment]
Hi @letmaik 

I do not know if this is a problem (from QGIS or gis4wrf) or if it is expected but saving the file and opening it in a new project was possible to export without this error

Thanks man
