### ISSUE TITLE
Run real error with "pid"

### ISSUE THREAD

**Issue by liaoyangsam** [GIS4WRF/gis4wrf#200]
**Describe the bug**

**To Reproduce**
1. Go to 'Simulation.'
2. Click on 'RUN.'
3. Scroll down to 'Run Real.'
WARNING    warning:/home/sam/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/plugin/ui/thread.py:85: ResourceWarning: unclosed file 
              if msg_type == 'pid':
             
             traceback: File "/home/sam/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/plugin/ui/thread.py", line 85, in run
              if msg_type == 'pid':
             

**Expected behavior**

**Screenshots**

**System Information (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - QGIS: [e.g. 3.16.1
![Screenshot from 2020-12-07 09-01-25](https://user-images.githubusercontent.com/1877508/101298935-31050200-386b-11eb-8811-aabefbd6c06c.png)
]

**Additional context**

**Comment by liaoyangsam** [comment]
warning:/home/sam/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/plugin/ui/thread.py:84: ResourceWarning: unclosed file 
              for msg_type, msg_val in run_program(self.path, self.cwd, self.error_pattern, self.use_mpi, self.mpi_processes):
             
             traceback: File "/home/sam/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/plugin/ui/thread.py", line 84, in run
              for msg_type, msg_val in run_program(self.path, self.cwd, self.error_pattern, self.use_mpi, self.mpi_processes):
             
![Uploading Screenshot from 2020-12-08 09-31-31.png…]()

**Comment by letmaik** [comment]
If this is still an issue, please provide the full error message.

**Comment by liaoyangsam** [comment]
It is Okay now, Something wrong on my setting.
