### ISSUE TITLE
Cannot delete / uninstall gis4wrf folder from C: drive

### ISSUE THREAD

**Issue by rsm278** [GIS4WRF/gis4wrf#204]
**Describe the bug**
I have been trying to uninstall gis4wrf and delete the 22gb folder in my C: drive, but when I press delete, nothing happens. I don't get any errors...it says it is deleting it, but then it is still there, and still 22gb.

**To Reproduce**
1. Go to C:\Users\remym\Documents\gis4wrf
2. Press Delete
3. It says it is deleting
4. it does not delete
**Expected behavior**
I expect it to delete!

**Screenshots**

**System Information (please complete the following information):**
Windows 10, Latest QGIS. 

**Additional context**

**Comment by dmey** [comment]
There is a known issue on Windows re deleting the geographical dataset folder. Can you please see if https://github.com/GIS4WRF/gis4wrf/issues/104#issuecomment-443720429 this solves it?

**Comment by rsm278** [comment]
I am not sure if I am doing this correct. I open the cmd and type in this based on comment 104:

comment : rd /q /s \\?\Z:\\test\\user1\\gis4wrf\\datasets\\geog\\con

What I typed: rd /q /s\\?\C:\\remym\\Documents\\gis4wrf

And it does nothing.

If I type like this:

rd /q /s\\?\C:\remym\Documents\gis4wrf it says access denied

Thx!

**Comment by dmey** [comment]
you need elevated privileges (i.e. run as admin)

**Comment by letmaik** [comment]
The correct command is `rd /q /s \\?\C:\remym\Documents\gis4wrf`. Admin privileges should not be necessary.

**Comment by dmey** [comment]
@rsm278 have you solved the issue?

**Comment by rsm278** [comment]
> @rsm278 have you solved the issue?

yes, just the way @letmaik said to do above.
