### ISSUE TITLE
Vertical interpolation in View menu

### ISSUE THREAD

**Issue by xinqu2016** [GIS4WRF/gis4wrf#205]
**Describe the bug**
After loading a raw wrfout file, I'd like to view geopotential height on 500 hPa. I know I need to interpolate the variable onto 500 hPa. I checked the Interpolate Vertical Level box, picked the hydrostatic pressure as the vertical variable and enter 500 in the Desired Level box. Then I click the Interpolate button. Got the following error:

plugins/gis4wrf/core/transforms/wrf_netcdf_to_gdal.py", line 162, in convert_wrf_nc_var_to_gdal_dataset
              assert len(dims) == len(shape), f'|{dims}| != |{shape}|'
             AssertionError: |('Time', 'south_north', 'west_east')| != |(399, 399)|

**To Reproduce**

**Expected behavior**

**Screenshots**

**System Information (please complete the following information):**
 - OS: Linux (ubuntu)
 - QGIS: 3.10.8-A Coruña
 - gis4wrf: 0.14.4
![Screenshot from 2021-02-01 22-26-43](https://user-images.githubusercontent.com/20599766/106561146-06d36780-64dd-11eb-803b-be612197b510.png)

**Additional context**

**Comment by dmey** [comment]
How many time steps does the wrfout contain?

**Comment by letmaik** [comment]
I assume a single time step. I put in a PR that fixes this case, but in the meantime I suggest to simply run WRF for at least two timesteps to avoid the issue.

**Comment by xinqu2016** [comment]
It's one timestep indeed. 

xinqu2016

**Comment by xinqu2016** [comment]
To confirm, the file needs to contain at two timesteps. The dimension of Time needs to be 2 or above. 

xinqu2016
