### ISSUE TITLE
Issue with Windows 8

### ISSUE THREAD

**Issue by AlexOvando** [GIS4WRF/gis4wrf#207]
After instalation in Qgis 3.12.3 . I got a message warning that the Windows version (i have tje 8) does not support the required Bluetooth API (image attached). How cann I solve that?
![image](https://user-images.githubusercontent.com/78741352/107230623-103d6200-69fe-11eb-8b1d-78f4b111355b.png)

**Comment by dmey** [comment]
Duplicate. Please see #103 for solution.
