### ISSUE TITLE
When I download data from website in GFS files,it tells_Program real.exe failed with errors, check the logs.

### ISSUE THREAD

**Issue by liaoyangsam** [GIS4WRF/gis4wrf#209]
Dear All,

My problem is as below:
**Program real.exe failed with errors, check the logs.**

**File "/home/xxm/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/plugin/ui/thread.py", line 85, in run
              self.use_mpi, self.mpi_processes):**
1. Go to 'Simulation'
2. Click on 'Run.'
3. Scroll down to 'Run Real'

**Should be without error**

**Screenshots**

**Ubuntu 18.04):**
 - OS: [e.g. Windows 10]
 - QGIS: [e.g. 3.16.3-Hannover]

Check the python and no idea how to change the code.
**   def run(self):
        try:
            for msg_type, msg_val in run_program(self.path, self.cwd, self.error_pattern,
                                                 self.use_mpi, self.mpi_processes):
                if msg_type == 'pid':
                    self.pid = msg_val
                elif msg_type == 'log':
                    self.output.emit(msg_val)
                elif msg_type == 'error':
                    self.error = msg_val
                else:
                    raise RuntimeError('Invalid output received: {}'.format(msg_type))
        except:
            self.exc_info = sys.exc_info()
![Screenshot from 2021-03-15 09-34-31](https://user-images.githubusercontent.com/1877508/111092735-d9fd8000-8571-11eb-9277-d9056e58b744.png)
**

Thanks very much for your kindly help.

**Comment by dmey** [comment]
can you check/send me the logs please

**Comment by liaoyangsam** [comment]
> can you check/send me the logs please

 Python warning:  traceback: File "/home/sam/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/plugin/ui/thread.py", line 85, in run
              self.use_mpi, self.mpi_processes):
message logs:  SUCCESS    GIS4WRF : Successfully prepared WRF files in /media/XXam/3b8d8124-e21a-45f4-8198-747c31594f9b/gis4wrfiles/xxxang/3-14-2021/run_wrf

**Comment by liaoyangsam** [comment]
> can you check/send me the logs please

 Python warning:  traceback: File "/home/sam/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/plugin/ui/thread.py", line 85, in run
              self.use_mpi, self.mpi_processes):
message logs:  SUCCESS    GIS4WRF : Successfully prepared WRF files in /media/XXam/3b8d8124-e21a-45f4-8198-747c31594f9b/gis4wrfiles/xxxang/3-14-2021/run_wrf

**Comment by dmey** [comment]
I don't see any errors. Check the outputs from `real.exe`.

**Comment by liaoyangsam** [comment]
> I don't see any errors. Check the outputs from `real.exe`.

![Screenshot from 2021-03-17 08-25-15](https://user-images.githubusercontent.com/1877508/111396913-0395e300-86fb-11eb-86f0-64eac445e9f3.png)
I can not open real.exe in my ubuntu 1804. 
And when I run real ,it show real with error, check logs, but messgae logs like this. and open the run.wrf, rsl.error.000 like this :
-------------- FATAL CALLED ---------------
 program wrf: error opening wrfinput_d01 for reading ierr=       -1021
-------------------------------------------
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 1

I doubt the domain problem.which I set up from website is not decimal number. 

Thanks 
Sam

**Comment by dmey** [comment]
It looks like a configuration issue. Can you please check that you can run the tutorial at https://gis4wrf.github.io/tutorials/gis4wrf/simulate-the-2018-european-heat-wave-with-gis4wrf. It this works then I would suggesting asking this in the WRF Forum at https://forum.mmm.ucar.edu/phpBB3/.

**Comment by liaoyangsam** [comment]
Now it appear like this after Run WRF. 
Backtrace for this error:
  + /home/sam/gis4wrf/dist/WRF-4.0-mpi/main/.libs/libgfortran-ed201abd.so.3.0.0(+0x13f59) [0x7fb0623aef59]
  + /home/sam/gis4wrf/dist/WRF-4.0-mpi/main/.libs/libgfortran-ed201abd.so.3.0.0(+0x1584e) [0x7fb0623b084e]
  + /home/sam/gis4wrf/dist/WRF-4.0-mpi/main/.libs/libgfortran-ed201abd.so.3.0.0(+0x146aa) [0x7fb0623af6aa]
  + /lib/x86_64-linux-gnu/libc.so.6(+0x3f040) [0x7fb061a33040]
  + /home/sam/gis4wrf/dist/WRF-4.0-mpi/main/wrf.exe() [0x1a3b7c9]
  + /home/sam/gis4wrf/dist/WRF-4.0-mpi/main/wrf.exe() [0x1a56c69]
  + /home/sam/gis4wrf/dist/WRF-4.0-mpi/main/wrf.exe() [0x1a6ae51]
  + /home/sam/gis4wrf/dist/WRF-4.0-mpi/main/wrf.exe() [0x1a7a5af]
  + /home/sam/gis4wrf/dist/WRF-4.0-mpi/main/wrf.exe() [0x14049dc]
  + /home/sam/gis4wrf/dist/WRF-4.0-mpi/main/wrf.exe() [0x1160fea]
  + /home/sam/gis4wrf/dist/WRF-4.0-mpi/main/wrf.exe() [0x1059ebf]
  + /home/sam/gis4wrf/dist/WRF-4.0-mpi/main/wrf.exe() [0xfb294a]
  + /home/sam/gis4wrf/dist/WRF-4.0-mpi/main/wrf.exe() [0xed91be]
  + /home/sam/gis4wrf/dist/WRF-4.0-mpi/main/wrf.exe() [0x40e3ba]
  + /home/sam/gis4wrf/dist/WRF-4.0-mpi/main/wrf.exe() [0x40d5af]
  + /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7fb061a15bf7]
  + /home/sam/gis4wrf/dist/WRF-4.0-mpi/main/wrf.exe() [0x40d5e9]
It is very strange for me. 
others run okay except data downloaded from NCAR.
Thanks.

**Comment by dmey** [comment]
Good, the WRF forum should be able to help you with specific configuration issues. I am going to close this now but feel free to update it once you solve the config/data issue.
