### ISSUE TITLE
AttributeError: module 'gis4wrf' has no attribute 'plugin' 

### ISSUE THREAD

**Issue by sirius25y** [GIS4WRF/gis4wrf#211]
I did "The 2018 European heat wave" tutorial and everything was successful until the final step: the "Visualize Output" for WRF. I received an error message shown below. Any ideas how to fix this?

**An error has occurred while executing Python code: 

AttributeError: module 'gis4wrf' has no attribute 'plugin'** 
Traceback (most recent call last):
  File "C:/Users/Michelle/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\plugin\ui\widget_view.py", line 255, in on_variable_selected
    self.replace_variable_layer()
  File "C:/Users/Michelle/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\plugin\ui\widget_view.py", line 298, in replace_variable_layer
    layer = gis4wrf.plugin.geo.load_layers([(uri, label, variable.name)],
AttributeError: module 'gis4wrf' has no attribute 'plugin'

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.14.1-Pi Pi, de08d6b71d 

Python Path:
C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python
C:/Users/Michelle/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Michelle/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS3~1.14\apps\Python37
C:\PROGRA~1\QGIS3~1.14\apps\Python37\Scripts
C:\Program Files\QGIS 3.14\bin\python37.zip
C:\PROGRA~1\QGIS3~1.14\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.14\apps\Python37\lib
C:\Program Files\QGIS 3.14\bin
C:\PROGRA~1\QGIS3~1.14\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.14\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.14\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.14\apps\Python37\lib\site-packages\Pythonwin
C:/Users/Michelle/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\Michelle\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms
C:\Users\Michelle\AppData\Local\gis4wrf\python37
C:\Users\Michelle\AppData\Local\gis4wrf\python37\lib\site-packages

**Comment by sirius25y** [comment]
Figured out my mistake. Can close this one now

**Comment by letmaik** [comment]
What was the issue?

**Comment by sirius25y** [comment]
All good. The issue was I thought i followed everything but got the start time wrong


Sent from Yahoo Mail for iPhone


On Wednesday, July 7, 2021, 5:03 pm, Maik Riechert ***@***.***> wrote:




What was the issue?
