### ISSUE TITLE
Couldn't load plugin 'gis4wrf' due to an error when calling its initGui() method

### ISSUE THREAD

**Issue by Zetison** [GIS4WRF/gis4wrf#213]
**Describe the bug**
When trying to load the GIS4WRF-plugin I get the following error. I expect this is because GIS4WRF is not supported by Ubuntu 20.x):

> Couldn't load plugin 'gis4wrf' due to an error when calling its initGui() method 
> 
> AttributeError: type object 'Qgis' has no attribute 'None' 
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/qgis/utils.py", line 360, in startPlugin
>     plugins[packageName].initGui()
>   File "/home/zetison/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/plugin/plugin.py", line 48, in initGui
>     self.init_logging()
>   File "/home/zetison/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/plugin/plugin.py", line 113, in init_logging
>     logging.NOTSET: getattr(Qgis, 'None'),
> AttributeError: type object 'Qgis' has no attribute 'None'
> 
> 
> Python version: 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0] 
> QGIS version: 3.20.0-Odense Odense, decaadbb31 

**To Reproduce**
Follow the installation guide https://gis4wrf.github.io/installation/

**System Information (please complete the following information):**
 - Ubuntu 20.04
 - QGIS: [e.g. 3.20.0]

**Comment by letmaik** [comment]
Thanks for reporting. This issue is unrelated to Ubuntu but rather to QGIS 3.20 which has a backwards-incompatible change. It's fixed in #215 and will be part of the next release. For now, I suggest using the previous QGIS version.
