### ISSUE TITLE
GIS4WRF plugin missing (?) on Ubuntu (Kubuntu) 18.04 LTS

### ISSUE THREAD

**Issue by gmaure** [GIS4WRF/gis4wrf#22]
Hi all,
I'd like to test the GIS4WRF plugin on my Ubuntu (Kubuntu) 18.04 LTS running QGIS 2.18.17, however GIS4WRF does not seem to show up on the list of available plugins...
Any idea on what would be the cause of this issue?
Genito

**Comment by dmey** [comment]
We do not support QGIS 2.x. Please follow the [installation instructions](https://github.com/GIS4WRF/gis4wrf/blob/master/INSTALL.md) to install QGIS 3.2.
