### ISSUE TITLE
RUN WRF error

### ISSUE THREAD

**Issue by ZhiCaoIE** [GIS4WRF/gis4wrf#226]
Command: C:\Program Files\Microsoft MPI\Bin\mpiexec.exe -n 20 C:\Users\caozh\Documents\gis4wrf\dist\WRF-4.0-mpi\main\wrf.exe
Working directory: C:/Users/caozh/Documents/gis4wrf/projects/China-1\run_wrf
 starting wrf task           16  of           20
 starting wrf task            0  of           20
 starting wrf task           13  of           20
 starting wrf task           15  of           20
 starting wrf task           18  of           20
 starting wrf task           17  of           20
 starting wrf task           19  of           20
 starting wrf task            6  of           20
 starting wrf task            8  of           20
 starting wrf task           12  of           20
 starting wrf task           11  of           20
 starting wrf task           10  of           20
 starting wrf task            5  of           20
 starting wrf task            7  of           20
 starting wrf task            4  of           20
 starting wrf task            2  of           20
 starting wrf task           14  of           20
 starting wrf task            3  of           20
 starting wrf task            1  of           20
 starting wrf task            9  of           20
 C:/projects/releases/WRF/frame/module_io_quilt_old.F        2933 F
Quilting with   1 groups of   0 I/O tasks.
 Ntasks in X            4 , ntasks in Y            5
*************************************
Configuring physics suite 'conus'

         mp_physics:      0*     0*
         cu_physics:      0*     0*
      ra_lw_physics:      4      4
      ra_sw_physics:      4      4
     bl_pbl_physics:      2      2
  sf_sfclay_physics:      2      2
 sf_surface_physics:      2      2

(* = option overrides suite setting)
*************************************
WRF V4.0 MODEL
 *************************************
 Parent domain
 ids,ide,jds,jde            1          71           1          71
 ims,ime,jms,jme           -4          25          -4          21
 ips,ipe,jps,jpe            1          18           1          14
 *************************************
DYNAMICS OPTION: Eulerian Mass Coordinate
   alloc_space_field: domain            1 ,              29672528  bytes allocated
 RESTART run: opening wrfrst_d01_2015-07-11_00_00_00 for reading
-------------- FATAL CALLED ---------------
program wrf: error opening   wrfrst_d01_2015-07-11_00_00_00 for reading
-------------------------------------------

job aborted:
[ranks] message

[0] application aborted
aborting MPI_COMM_WORLD (comm=0x44000000), error 1, comm rank 0

[1] application aborted
aborting MPI_COMM_WORLD (comm=0x44000000), error 1, comm rank 1

[2] application aborted
aborting MPI_COMM_WORLD (comm=0x44000000), error 1, comm rank 2

[3] application aborted
aborting MPI_COMM_WORLD (comm=0x44000000), error 1, comm rank 3

[4] application aborted
aborting MPI_COMM_WORLD (comm=0x44000000), error 1, comm rank 4

[5] application aborted
aborting MPI_COMM_WORLD (comm=0x44000000), error 1, comm rank 5

[6] application aborted
aborting MPI_COMM_WORLD (comm=0x44000000), error 1, comm rank 6

[7] application aborted
aborting MPI_COMM_WORLD (comm=0x44000000), error 1, comm rank 7

[8-15] terminated

[16] application aborted
aborting MPI_COMM_WORLD (comm=0x44000000), error 1, comm rank 16

[17] application aborted
aborting MPI_COMM_WORLD (comm=0x44000000), error 1, comm rank 17

[18] application aborted
aborting MPI_COMM_WORLD (comm=0x44000000), error 1, comm rank 18

[19] application aborted
aborting MPI_COMM_WORLD (comm=0x44000000), error 1, comm rank 19

---- error analysis -----

[0-7,16-19] on DESKTOP-7T62C3L
C:\Users\caozh\Documents\gis4wrf\dist\WRF-4.0-mpi\main\wrf.exe aborted the job. abort code 1

---- error analysis -----
Assertion failed in e:\bt\909353\repo\src\mpi\mpiexec\mpiexec_handle_command.cpp(2077): pg != nullptr
Runtime: 1 s

------------------------------------------------------------------------------------
Additional info:

------------------------------------------------------------------------------------
namelist.wps

&share
nocolons = .true.
max_dom = 2
start_date = '2015-07-11_00:00:00', '2015-07-11_00:00:00'
end_date = '2015-07-11_12:00:00', '2015-07-11_12:00:00'
interval_seconds = 21600
/

&geogrid
parent_id = 1, 1
parent_grid_ratio = 1, 4
i_parent_start = 1, 11
j_parent_start = 1, 11
e_we = 71, 201
e_sn = 71, 201
map_proj = 'lambert'
dx = 4000.0
dy = 4000.0
ref_lon = 115.0
ref_lat = 35.0
geog_data_res = 'lowres', 'lowres'
geog_data_path = 'C:\Users\caozh\Documents\gis4wrf\datasets\geog/'
truelat1 = 33.5
truelat2 = 30.0
stand_lon = 127.0
/

&metgrid
fg_name = 'FILE'
/

------------------------------------------------------------------------------------
namelist.input

&time_control
start_year = 2015, 2015
start_month = 7, 7
start_day = 11, 11
start_hour = 0, 0
end_year = 2015, 2015
end_month = 7, 7
end_day = 11, 11
end_hour = 12, 12
interval_seconds = 21600
input_from_file = .true., .true.
history_interval = 10, 10
frames_per_outfile = 100, 100
restart = .true.
restart_interval = 7200
io_form_history = 2
io_form_restart = 2
io_form_input = 2
io_form_boundary = 2
start_minute = 0, 0
start_second = 0, 0
end_minute = 0, 0
end_second = 0, 0
nocolons = .true.
/

&domains
time_step = 40
time_step_fract_num = 0
time_step_fract_den = 1
max_dom = 2
e_we = 71, 201
e_sn = 71, 201
e_vert = 33, 33
p_top_requested = 5000
num_metgrid_levels = 27
num_metgrid_soil_levels = 4
dx = 4000.0, 1000.0
dy = 4000.0, 1000.0
grid_id = 1, 2
parent_id = 1, 1
i_parent_start = 1, 11
j_parent_start = 1, 11
parent_grid_ratio = 1, 4
parent_time_step_ratio = 1, 4
feedback = 1
smooth_option = 0
/

&physics
physics_suite = 'CONUS'
mp_physics = 0, 0
cu_physics = 0, 0
radt = 9, 3
bldt = 0, 0
cudt = 0, 0
icloud = 0
num_land_cat = 21
sf_urban_physics = 1, 1
/

&dynamics
hybrid_opt = 2
w_damping = 0
diff_opt = 1, 1
km_opt = 4, 4
diff_6th_opt = 0, 0, 0
diff_6th_factor = 0.12, 0.12
base_temp = 290.0
damp_opt = 3
zdamp = 5000.0, 5000.0
dampcoef = 0.2, 0.2
khdif = 0, 0
kvdif = 0, 0
/

&bdy_control
spec_bdy_width = 5
specified = .true.
/

&namelist_quilt
/

**Comment by letmaik** [comment]
The important bit from your copy paste is the error:
> RESTART run: opening wrfrst_d01_2015-07-11_00_00_00 for reading
-------------- FATAL CALLED ---------------
program wrf: error opening wrfrst_d01_2015-07-11_00_00_00 for reading

This doesn't look like a GIS4WRF issue. See https://www2.mmm.ucar.edu/wrf/users/docs/user_guide_v4/v4.3/users_guide_chap5.html#restart for how restart runs work in WRF or alternatively post in the official WRF discussion forums.
