### ISSUE TITLE
Error during plugin loading: "TypeError: setFixedWidth(self, int): argument 1 has unexpected type 'float'"

### ISSUE THREAD

**Issue by bakamotokatas** [GIS4WRF/gis4wrf#229]
**Describe the bug**
The GIS4WRF plugin is not working I guess since I updated python to 3.10.1.

Couldn't load plugin 'gis4wrf' due to an error when calling its classFactory() method 

RuntimeError: GIS4WRF: Error installing Python packages Log: Added /home/bakamotokatas/.local/share/gis4wrf/python310/lib/python3.10/site-packages as module search path 
Traceback (most recent call last):
  File "/home/bakamotokatas/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/__init__.py", line 53, in bootstrap_with_ui
    dialog = WaitDialog(parent, PLUGIN_NAME)
  File "/home/bakamotokatas/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/plugin/ui/helpers.py", line 266, in __init__
    self.setFixedWidth(parent.width() * 0.5)
TypeError: setFixedWidth(self, int): argument 1 has unexpected type 'float'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/bakamotokatas/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/__init__.py", line 22, in classFactory
    bootstrap_with_ui(iface)
  File "/home/bakamotokatas/.local/share/QGIS/QGIS3/profiles/default/python/plugins/gis4wrf/__init__.py", line 62, in bootstrap_with_ui
    raise RuntimeError(PLUGIN_NAME + ': Error installing Python packages\nLog:\n' + log) from e
RuntimeError: GIS4WRF: Error installing Python packages
Log:
Added /home/bakamotokatas/.local/share/gis4wrf/python310/lib/python3.10/site-packages as module search path

**To Reproduce**
When I open QGIS it gives this error.

**Expected behaviour**
When I open QGIS, GIS4WRF should work fine.

**Screenshots**
![image](https://user-images.githubusercontent.com/22841746/151958352-022614d6-eb30-4a1f-967e-fc3eb313e39b.png)

**System Information (please complete the following information):**
 - OS: Manjaro 21.2.2
 - QGIS: 3.22.3-Białowieża
 - GIS4WRF version 0.14.6
 - Qt version 5.15.2
 - Python version 3.10.1
 - GDAL/OGR version 3.4.0
 - PROJ version 8.2.0
 - EPSG Registry database version v10.038 (2021-10-21)
 - GEOS version 3.9.1-CAPI-1.14.2
 - SQLite version 3.37.2
 - PDAL version 2.3.0
 - PostgreSQL client version 13.4
 - SpatiaLite version 5.0.1
 - QWT version 6.2.0
 - QScintilla2 version 2.13.1

**Comment by letmaik** [comment]
Thanks for reporting. The error "TypeError: setFixedWidth(self, int): argument 1 has unexpected type 'float'" is related to Qt, which probably was caused by a version update. I've put in a PR https://github.com/GIS4WRF/gis4wrf/pull/230 which should fix it. If you want, you can manually apply this patch to the relevant Python files of gis4wrf, just need to figure out where QGIS stores plugins.

**Comment by bakamotokatas** [comment]
Hello, thank you for the fix. I applied the patch manually and the plugin is working now.
