### ISSUE TITLE
Met dataset ds090.0 lists no products

### ISSUE THREAD

**Issue by letmaik** [GIS4WRF/gis4wrf#24]
![image](https://user-images.githubusercontent.com/530988/42342091-0ab899d8-808d-11e8-9d80-303637acaf4b.png)

The others are working.

**Comment by dmey** [comment]
There appears with the RDA server in accessing the `ds090.0`.
Error reported to UCAR maintainer (https://rda.ucar.edu/datasets/ds090.0/). Awaiting response -- will update once resolved.

**Comment by dmey** [comment]
The `ds090.0` dataset can now be accessed online however it is not supported by the [RDA API](https://rda.ucar.edu/#!apps_api_desc). I will therefore remove it from the list of downloadable met datasets for now -- we can revisit this decision if there is enough demand.
