### ISSUE TITLE
'Export to namelist' button raises error

### ISSUE THREAD

**Issue by thierryhedde** [GIS4WRF/gis4wrf#26]
Une erreur est survenue lors de l'éxécution du code Python: 

AttributeError: 'Project' object has no attribute 'export_namelists' 
Traceback (most recent call last):
  File "C:/Users/th137147/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\plugin\ui\widget_domains.py", line 282, in on_export_geogrid_namelist_button_clicked
    self.project.export_namelists(folder)
AttributeError: 'Project' object has no attribute 'export_namelists'

Version de Python : 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] 
Version de QGIS : 3.2.0-Bonn Bonn, bc43194061 

Chemin Python :
C:/PROGRA~1/QGIS3~1.2/apps/qgis/./python
C:/Users/th137147/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/th137147/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.2/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.2\bin\python36.zip
C:\PROGRA~1\QGIS3~1.2\apps\Python36\DLLs
C:\PROGRA~1\QGIS3~1.2\apps\Python36\lib
C:\Program Files\QGIS 3.2\bin
C:\PROGRA~1\QGIS3~1.2\apps\Python36
C:\PROGRA~1\QGIS3~1.2\apps\Python36\lib\site-packages
C:\PROGRA~1\QGIS3~1.2\apps\Python36\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.2\apps\Python36\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.2\apps\Python36\lib\site-packages\Pythonwin
C:/Users/th137147/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\th137147\AppData\Local\gis4wrf\python
C:\Users\th137147\AppData\Local\gis4wrf\python\lib\site-packages
C:/Users/th137147/Documents/gis4wrf

**Comment by dmey** [comment]
I renamed the title to reflect the concrete issue you encountered. I could reproduce it and will fix it soon. Thanks for reporting it!

About your other concern, we do wrap the majority of possible error conditions with QGIS's native error reporting mechanisms; e.g. using the QGIS message bar or using message boxes when we requrire immediate user attention. Please open a new issue for the concrete error condition where this is not the case yet. You should always be able -- even in those cases -- to see the error message by clicking on the "Stack Trace" button if an exception is raised that is not currently wrapped nicely as described above.

**Comment by dmey** [comment]
Just to let you know that I have just fixed this on `master`. There are still a couple of issue I want to address first before releasing the next version (see https://github.com/GIS4WRF/gis4wrf/milestone/2) but will do so soon. If you have GIS4WRF installed on your system you will be notified automatically when the new version is released.
