### ISSUE TITLE
Bug gis4wrf in ubuntu 18.04

### ISSUE THREAD

**Issue by ratovohasy** [GIS4WRF/gis4wrf#30]
Hello world,
I' m using extensions Gis4wrf, the problem it isthat the extension cannot be used because of thiserror that I send to you in attachment.
Thank you very much of your assistance and forinformation I use qgis 3.2 in ubuntu 18.04.
Cordially,
![qgis_problem](https://user-images.githubusercontent.com/41721651/43244955-3e7b8fea-90b5-11e8-8fd9-176b3567b61a.png)

**Comment by letmaik** [comment]
Installation is currently not fully automated on Ubuntu. Please follow the instructions at https://github.com/GIS4WRF/gis4wrf/blob/master/INSTALL.md#ubuntu. It should only take a few minutes.

**Comment by ratovohasy** [comment]
Dear Letmaik, I have already done this method but the problem is that I still get this error.

**Comment by letmaik** [comment]
It seems like f90nml is missing in your installation. Are you sure you installed that one correctly? You can check what you've installed with `pip3 freeze`.

**Comment by ratovohasy** [comment]
Dear Letmaik,
I uninstalled my Qgis and I remade the proposals that you told me and then my extension gis4wrf goes to wonder.
Thank you very much,
