### ISSUE TITLE
LU_INDEX data cannot be displayed

### ISSUE THREAD

**Issue by iliasaga** [GIS4WRF/gis4wrf#38]
While all other data of geo_em.d0x.nc files open in the Map canvas without a problem, the LU_INDEX results in an error:

Traceback (most recent call last):
  File "C:/Users/Ilias/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\plugin\ui\widget_view.py", line 209, in on_variable_selected
    self.replace_variable_layer()
  File "C:/Users/Ilias/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\plugin\ui\widget_view.py", line 249, in replace_variable_layer
    dataset.path, variable.name, extra_dim_index, interp_level, interp_vert_name)
  File "C:/Users/Ilias/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gis4wrf\core\transforms\wrf_netcdf_to_gdal.py", line 244, in convert_wrf_nc_var_to_gdal_dataset
    ''').format(name=subdataset_name, band=band_idx, rows=rows, cols=cols)}, 'vrt_sources')
  File "C:\OSGEO4~1\apps\Python36\lib\site-packages\osgeo\gdal.py", line 1475, in SetMetadata
    return _gdal.MajorObject_SetMetadata(self, *args)
RuntimeError: `HDF5:"C:/Users/Ilias/Desktop/test/geo_em.d02.nc"://LU_INDEX' does not exist in the file system, and is not recognized as a supported dataset name.

 - OS: Windows 10
 - QGIS 3.2.2

**Comment by dmey** [comment]
Thanks for reporting this issue. Can you please let me know the following:

- Do you encounter the issue also when viewing wrf output files (`wrfout_`...)? 
- What version of GDAL are you running with QGIS? You can find this in QGIS > Help > About menu.

It may also be good if you can attach the file you are trying to open (`geo_em.d02.nc`).

**Comment by iliasaga** [comment]
I haven't managed to open wrfout files, as it seems not to properly recognize them, but I haven't searched much for it and it seems a different, if any, issue.

All other WPS data, for example WPS binary files, open without any problems.
The same with other variables of the geo_em.nc  file (e.g. LANDUSEF).
When I open the geo_em.nc without the plugin, as a raster layer, LU_INDEX does open, although as expected not georeferenced properly.

GDAL version 2.2.4
[geo_em.d02.nc.zip](https://github.com/GIS4WRF/gis4wrf/files/2368536/geo_em.d02.nc.zip)

**Comment by dmey** [comment]
Thank you both for the reports. This has now been fixed in [master](https://github.com/GIS4WRF/gis4wrf/commit/32f5aca19d1b53b4be10d97e94c9bf918851858f) and will be part of the next release which will be released soon.

**Comment by iliasaga** [comment]
Now it opens the LU_INDEX, but flipped. All other data have the correct orientation.
Please see attachment:
[examples.zip](https://github.com/GIS4WRF/gis4wrf/files/2370426/examples.zip)

**Comment by dmey** [comment]
[This](https://github.com/GIS4WRF/gis4wrf/tree/dmey/flip_HDF5) should fix the issue -- I will create a PR before releasing a new version of GIS4WRF.
@letmaik I am just keeping this seperate for now just in case we want to make other small changes/refactoring.

**Comment by iliasaga** [comment]
Yes, it did. Thank you for the quick fix.
