### ISSUE TITLE
Cannot rerun WPS/WRF if output file is open or has been viewed Windows

### ISSUE THREAD

**Issue by dmey** [GIS4WRF/gis4wrf#41]
The typcal locking of files on Windows... Rerunning WPS/WRF after a file has been opened and closed results in PermissionError on Windows:

```
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process
```

This is really a driver (GDAL) problem but we should handle it in some way.

**Comment by dmey** [comment]
At the moment when the files are added to the list in `GIS4WRF Dock` > `View` >  `Dataset` cannot be removed.

**Comment by letmaik** [comment]
I thought I had fixed that, hmm, need to do some more investigations.

**Comment by letmaik** [comment]
I could reproduce one specific issue which happened when for some reason the opening of a variable failed. Then this wouldn't close the netcdf dataset properly. This is now fixed and was not related to GDAL. There is still the issue with VRT datasets with GDAL, which at the moment we only use for LU_INDEX, E, and F variables. If you can reproduce it for any other variables while never selecting the three mentioned ones, then that would be yet another case worth root causing.
