### ISSUE TITLE
Please add valid maintainer

### ISSUE THREAD

**Issue by pcav** [GIS4WRF/gis4wrf#46]
currently it's a weird `ce7wpv7vyit0w3mxlqqn`

**Comment by dmey** [comment]
The maintainer `username` has not been changed since the first version we released and it is still valid -- It's just a random string.

**Comment by pcav** [comment]
Exactly - we are implementing more predictable and reliable metadata. Please add one.
Thanks.

**Comment by letmaik** [comment]
@pcav There is a misunderstanding. The current username *is* the actual username. It just looks odd, but it's the username.

**Comment by pcav** [comment]
Oh, I see, sorry.
