### ISSUE TITLE
Using Mesh layer to display output

### ISSUE THREAD

**Issue by saberraz** [GIS4WRF/gis4wrf#47]
Currently the outputs are loaded back in QGIS as a raster. Ideally you should use mesh layer API to load the grib directly in QGIS 3.2+:
https://twitter.com/lutraconsulting/status/1018809991103500288

If your output contains vector, it will be displayed as a part of your mesh layer. You can also explore the time dimension.

**Comment by letmaik** [comment]
Do you have any more documentation or tutorial/example on how to do that exactly?

**Comment by saberraz** [comment]
It is a very recent feature (for background reading: https://github.com/qgis/QGIS-Enhancement-Proposals/issues/119).

The idea is to use mesh layer (if supported by mdal, which grib is supported) in addition to gda/ogr.
Here is the API:
https://qgis.org/api/classQgsMeshLayer.html

For example for a grib file you just do `QgsMeshLayer (“path/to/file.grb”, “my layer”, “mdal”)`

If you are using a custom mesh, you can add it to mdal here:
https://github.com/lutraconsulting/MDAL
A copy of the code at the moment is shipped with QGIS:
https://github.com/qgis/QGIS/tree/master/external/mdal

Let us know if you need help.

Cheers
Saber

**Comment by saberraz** [comment]
At the moment, mdal does not support netcdf. For the vectors, it autodetects the vectors. As long as you can read the nc file with cdo, ncdump or gdalinfo, it will be easy to guess various quantities.

You can still load your nc data as gdal layer obviously. But we are planning to add 3D support for mesh layer in future which will not display your nc file with the correct z scale if it is loaded as raster.....

**Comment by letmaik** [comment]
I'm closing this for now since there is nothing for us to do here at the moment. Feel free to ping us again once MDAL supports NetCDF.
