### ISSUE TITLE
Offer possibility to change pixel values in WRF netcdf data

### ISSUE THREAD

**Issue by hugohartmann** [GIS4WRF/gis4wrf#57]
**Is your feature request related to a problem? Please describe.**
We sometimes notice that geographical data is not everywhere correct (landuse in south-west NL shows glacier, which in fact is an area with a lot of green-houses). 
**Describe the solution you'd like**
Offer the possibility to change data in WRF netcdf files, like the geo_em file. Pick a pixel (or select pixels with a polygon tool), change its value(s) and write the file

**Comment by dmey** [comment]
One of the main reasons we created GIS4WRF was to make sure that data from/to WPS/WRF is converted 'correctly' therefore, my main concern here, would be to understand why this is not the case -- there should be no reason to have have different results if the data are interpolated from/to the same spatial resolution.
Having said this, I think that there are ways to do this programmatically or with other plug-ins in QGIS (e.g. see [this](https://gis.stackexchange.com/questions/40873/how-to-modify-single-pixel-values-in-qgis)). Perhaps this is something that we can explain through a tutorial!? I have created a new issue about new tutorials we can add to the current website (see #88). If you think that issue could make an interesting tutorial please add it to the list in #88.

**Comment by letmaik** [comment]
Closing as out of scope, probably better handled by existing QGIS plugins to modify rasters and as @dmey said can be explained in a tutorial (see #88).

**Comment by dmey** [comment]
Until the tutorial is ready you can use https://www.lutraconsulting.co.uk/blog/2016/09/05/serval/ -- it is straightforward to use but remember to to save the wrf layers as raster before being able to change values with Serval.
