### ISSUE TITLE
WRF tutorial Amsterdam does not run on 8 cores

### ISSUE THREAD

**Issue by hugohartmann** [GIS4WRF/gis4wrf#58]
**Describe the bug**
The WRF tutorial does not run on 8 cores, 4 cores, neither. 2 cores is OK

**Expected behavior**
Mention on the page that it only runs with 2 cores as the tutorial domain is too small to be paralellized.

**Operating System Information (please complete the following information):**
Windows 10

**Comment by dmey** [comment]
I seem to remember to have tested this on a machine with more than 2 cores.
@letmaik can you see if you can run this with more than 2 cores? Else I will check myself on Thursday.

**Comment by dmey** [comment]
@hugohartmann I have just checked and I was able to run it on 6 cores but not 8.
Can you please attach the log of a case with 4 cores?

**Comment by hugohartmann** [comment]
Hi,  I rechecked, 4 and 6 work on my side as well (probably I was mixed up). 8 not, so the tutorial should state that max 6 cores should be selected to run this case. 

LOG: 

Command: C:\Program Files\Microsoft MPI\Bin\mpiexec.exe -n 8 C:\Users\hugo\Documents\gis4wrf\dist\WRF-4.0-mpi\main\wrf.exe
Working directory: C:/Users/hugo/Documents/gis4wrf/projects/test3\run_wrf
 starting wrf task            0  of            8
 starting wrf task            6  of            8
 starting wrf task            4  of            8
 starting wrf task            3  of            8
 starting wrf task            7  of            8
 starting wrf task            5  of            8
 starting wrf task            2  of            8
 starting wrf task            1  of            8
 C:/projects/releases/WRF/frame/module_io_quilt_old.F        2933 F
Quilting with   1 groups of   0 I/O tasks.
 Ntasks in X            2 , ntasks in Y            4
*************************************
Configuring physics suite 'conus'

         mp_physics:      0*     0*
         cu_physics:      0*     0*
      ra_lw_physics:      4      4
      ra_sw_physics:      4      4
     bl_pbl_physics:      2      2
  sf_sfclay_physics:      2      2
 sf_surface_physics:      2      2

(* = option overrides suite setting)
*************************************
   For domain            1 , the domain size is too small for this many processors, or the decomposition aspect ratio is poor.
   Minimum decomposed computational patch size, either x-dir or y-dir, is 10 grid cells.
  e_we =    31, nproc_x =    2, with cell width in x-direction =   15
  e_sn =    31, nproc_y =    4, with cell width in y-direction =    7
  --- ERROR: Reduce the MPI rank count, or redistribute the tasks.
   For domain            2 , the domain size is too small for this many processors, or the decomposition aspect ratio is poor.
   Minimum decomposed computational patch size, either x-dir or y-dir, is 10 grid cells.
  e_we =    31, nproc_x =    2, with cell width in x-direction =   15
  e_sn =    31, nproc_y =    4, with cell width in y-direction =    7
  --- ERROR: Reduce the MPI rank count, or redistribute the tasks.
-------------- FATAL CALLED ---------------
NOTE:       1 namelist settings are wrong. Please check and reset these options
-------------------------------------------

job aborted:
[ranks] message

[0] application aborted
aborting MPI_COMM_WORLD (comm=0x44000000), error 1, comm rank 0

[1] application aborted
aborting MPI_COMM_WORLD (comm=0x44000000), error 1, comm rank 1

[2] application aborted
aborting MPI_COMM_WORLD (comm=0x44000000), error 1, comm rank 2

[3] application aborted
aborting MPI_COMM_WORLD (comm=0x44000000), error 1, comm rank 3

[4] application aborted
aborting MPI_COMM_WORLD (comm=0x44000000), error 1, comm rank 4

[5] application aborted
aborting MPI_COMM_WORLD (comm=0x44000000), error 1, comm rank 5

[6] application aborted
aborting MPI_COMM_WORLD (comm=0x44000000), error 1, comm rank 6

[7] application aborted
aborting MPI_COMM_WORLD (comm=0x44000000), error 1, comm rank 7

---- error analysis -----

[0-7] on LT-HUGO3
C:\Users\hugo\Documents\gis4wrf\dist\WRF-4.0-mpi\main\wrf.exe aborted the job. abort code 1

---- error analysis -----
Exit code: 1
Runtime: 4 s

**Comment by dmey** [comment]
@hugohartmann let me know if you think [this]( https://github.com/GIS4WRF/gis4wrf.github.io/commit/5473a14a91e919e18426f3f34abf4292fd0003c9) is clear enough. For updated web page see https://gis4wrf.github.io/tutorials/.
