### ISSUE TITLE
Indicate the meaning of "*" in variable names when visualizing WRF outputs

### ISSUE THREAD

**Issue by letmaik** [GIS4WRF/gis4wrf#66]
We use [wrf-python](https://wrf-python.readthedocs.io/en/latest/diagnostics.html) to show derived variables. These are indicated with a trailing `*` in the variable list in the View tab. It would be good to add a note in some form in this tab that explains what `*` variables are and that they are produced by wrf-python.

**Comment by dmey** [comment]
Maybe use a tooltip with somethiing like `Derived variable with wrf-python`
