### ISSUE TITLE
Export graphs/animation to file

### ISSUE THREAD

**Issue by hugohartmann** [GIS4WRF/gis4wrf#77]
**Is your feature request related to a problem? Please describe.**
In GIS4WRF wrf results can be visualized, but not exported to a file (e.g. PNG, or animated GIF)
**Describe the solution you'd like**
Add feature to export to file.

**Comment by letmaik** [comment]
You can export a single layer by right-clicking on the layer name -> Export -> Save as... Then choose rendered image, and format GeoTIFF. There doesn't seem to be support for PNG, but once you have the TIFF, you can open with any image editing tool. This doesn't include a legend or coordinate axes out of the box. You can add these by creating a print layout with Project -> New Print Layout, but this means manually arranging things and is probably not directly what you want. If there is a way to create a print layout programmatically, then this may be a compromise.

Supporting export as animations is tricky in general, I'm not sure what the best way would be to realize that.

You may also find https://wrf-python.readthedocs.io/en/latest/plot.html#plotting-examples useful which would give you much more control over the plots you want to create.

Which of those options would work best for you?

**Comment by hugohartmann** [comment]
Thanks for pointing me to these python scripts. 

My impression is that GIS4WRF is a great tool for setting up and running a WRF case study. It also offers the possibility to quickly analyse results. However, if you would like to do a thorough analysis of the results with production of nice graphs, I need to do this separately (through python scripts or NCL) as QGIS does not support the sophisticated research analysis requirements. If you agree with me, then we can close this issue.

**Comment by letmaik** [comment]
I would agree to that. @dmey You too?
If there is something that is useful for preparing/running/checking simulations, then this is a good candidate for a GIS4WRF feature. For example, if there is a certain type of plot or visualization that the majority of people using WRF typically want to look at (independent of creating publication-quality analyses/plots), then maybe that's something for GIS4WRF. We have to find a good balance here I think.
