### ISSUE TITLE
Please add a valid email

### ISSUE THREAD

**Issue by pcav** [GIS4WRF/gis4wrf#8]
as Author's email
Thanks.

**Comment by dmey** [comment]
I would prefer to not add an email address as feedback/contact channel but rather rely on GitHub issues -- is the author's email address used for anything else in the QGIS plugin repository, or just as a contact option for users? I noticed that the email address is *not* shown on the public QGIS plugin repository website but it is visible after users install the plugin -- was this an attempt to protect the author's email address? In general, for my needs, maintaining an additional email address for GIS4WRF would simply increase my overheads and perhaps make users less likely to use GitHub issues.

**Comment by pcav** [comment]
the email is not visible to uesrs, we need for admin purposes

**Comment by dmey** [comment]
I have already registered an email address with OSGeo, is there any chance you could use that instead? If I add an email address to `metadata.txt`, the address will be visible to anyone who accesses the GIS4WRF repository on GitHub, or to anyone who clicks on the Author's name after the plug-in has been installed.

**Comment by pcav** [comment]
True. However, this is not an issue for the 700+ plugins already published. I agree that we could improve the privacy of the author. Could you please file a ticket on the plugin infrastructure, and possibly also discuss about this in the `qgis-dev` mailing list?
Thanks a lot.

**Comment by dmey** [comment]
@letmaik this looks like it will take a while, so will add an email address for now. Could you please open an issue on the [QGIS issue tracker](https://issues.qgis.org/projects/qgis/issues/)?
@pcav I have added an email address for now until this issue is addressed.
