### ISSUE TITLE
Add parameter dimension and unit to the parameter description

### ISSUE THREAD

**Issue by hugohartmann** [GIS4WRF/gis4wrf#80]
**Is your feature request related to a problem? Please describe.**
The view tab shows the list of parameters in short name and long name, but the parameter dimension (2D or 3D field) and unit is missing.
**Describe the solution you'd like**
Please add parameter dimension and unit to the parameter list in the view tab.

**Comment by letmaik** [comment]
About the units:

![grafik](https://user-images.githubusercontent.com/530988/46249026-01037e00-c41a-11e8-9cb7-ee2b2d583f6f.png)

All derived variables have units, and the variables coming directly from the file take the units that are stored in the metadata of the file. I couldn't find any variables in WRF output files that are lacking units. Can you provide some examples?

**Comment by hugohartmann** [comment]
Hmm, I believe it was a hick-up. I re-opened QGIS and now it correctly displayed the parameters with units.
