### ISSUE TITLE
Linux: Real and WRF fail with segmentation fault when using multiple cores

### ISSUE THREAD

**Issue by dmey** [GIS4WRF/gis4wrf#81]
Running either Real/WRF for the tutorial found at https://gis4wrf.github.io/tutorials/ on Ubuntu (Bionic) with the latest mpi-enabled pre-built binaries results in the following segmentation fault after calling `HALO_EM_VINTERP_UV_1_inline.inc`: 

```
d01 2018-07-15_12:00:00 calling inc/HALO_EM_VINTERP_UV_1_inline.inc

Program received signal 11 (SIGSEGV): Segmentation fault.

Backtrace for this error:
  + /home/testing/gis4wrf/dist/WRF-4.0-mpi/main/.libs/libgfortran-ed201abd.so.3.0.0(+0x13f59) [0x7f0125efef59]
  + /home/testing/gis4wrf/dist/WRF-4.0-mpi/main/.libs/libgfortran-ed201abd.so.3.0.0(+0x1584e) [0x7f0125f0084e]
  + /home/testing/gis4wrf/dist/WRF-4.0-mpi/main/.libs/libgfortran-ed201abd.so.3.0.0(+0x146aa) [0x7f0125eff6aa]
  + /lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7f0125582f20]
  + /home/testing/gis4wrf/dist/WRF-4.0-mpi/main/real.exe() [0x22613f7]
  + /home/testing/gis4wrf/dist/WRF-4.0-mpi/main/real.exe() [0x11b6e9f]
  + /home/testing/gis4wrf/dist/WRF-4.0-mpi/main/real.exe() [0x4d0be4]
  + /home/testing/gis4wrf/dist/WRF-4.0-mpi/main/real.exe() [0x5002f2]
  + /home/testing/gis4wrf/dist/WRF-4.0-mpi/main/real.exe() [0x47b5ca]
  + /home/testing/gis4wrf/dist/WRF-4.0-mpi/main/real.exe() [0x47cec8]
  + /home/testing/gis4wrf/dist/WRF-4.0-mpi/main/real.exe() [0x469e33]
  + /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f0125565b97]
  + /home/testing/gis4wrf/dist/WRF-4.0-mpi/main/real.exe() [0x469e65]

```
The above error is not triggered when running the case using a single core or when running the case on either Windows or macOS. I have attached logfiles produced from real using 1 and 2 cores on Linux (Bionic) and macOS (High Sierra).

[rsl.error.0000-macos-1-core-success.txt](https://github.com/GIS4WRF/gis4wrf/files/2431538/rsl.error.0000-macos-1-core-success.txt)
[rsl.error.0000-macos-2-cores-success.txt](https://github.com/GIS4WRF/gis4wrf/files/2431539/rsl.error.0000-macos-2-cores-success.txt)
[rsl.error.0000-ubuntu-bionic-2-cores-fail.txt](https://github.com/GIS4WRF/gis4wrf/files/2431540/rsl.error.0000-ubuntu-bionic-2-cores-fail.txt)
[rsl.error.0000-ubuntu-bionic-1-core-success.txt](https://github.com/GIS4WRF/gis4wrf/files/2431541/rsl.error.0000-ubuntu-bionic-1-core-success.txt)

**Comment by letmaik** [comment]
This is fixed, it was an issue with the pre-built binaries for Linux for which I uploaded fixed versions.
