### ISSUE TITLE
Please add a home page

### ISSUE THREAD

**Issue by pcav** [GIS4WRF/gis4wrf#9]
If nothing more descriptive is available, the GH repo address can do it.
Thanks.

**Comment by dmey** [comment]
If it is OK with you, I would rather leave out the home page for now as this is not one of the required metadata entries (https://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/plugins.html#id5).

**Comment by pcav** [comment]
It is not required, but would be nice for completeness anyway. Anything wrong to put https://github.com/GIS4WRF/gis4wrf for now?

**Comment by dmey** [comment]
Done
